#!/usr/bin/env python3
"""RBAC vocabulary generator (E09-T03).

Reads the single canonical registry — the `x-rbac.permissions` blocks in
`docs/plan/22-api-openapi.yaml` — and regenerates two committed artefacts
that must never be hand-edited:

1. `services/api/candleviewer/auth/generated_permissions.py` — the
   `Permission` `StrEnum` consumed by `docs/plan/24-internal-schemas.md`
   §15.2 and by `services/api/candleviewer/auth/scopes.py`.
2. `services/api/candleviewer/auth/rbac_seed.json`'s `permissions` list
   (roles / role_permissions stay hand-authored — the vocabulary itself is
   what the OpenAPI document owns; which system role gets which permission
   is a policy decision recorded once, in the seed file, per the ticket's
   "Role seeds" scope note).

`--check` (used by CI job `generated-code`) writes nothing and exits
non-zero if the working tree's committed files would change — the same
convention as `tools/gen/export_instrument_policy_rules.py`.

`--out-dir <dir>` redirects both outputs to `<dir>` (the seed is still *read*
from the committed path). Tests use this to exercise the write path inside
`tmp_path` without ever touching the checkout (C-13.7). Files are always
written with LF line endings, byte-identical on every platform, matching
`.gitattributes`.

Stdlib + PyYAML only; no network. Every operation with an `x-rbac` block
must declare `is_dangerous` implicitly via the seed's own `dangerous` flag
(carried over unchanged from `rbac_seed.json`'s existing per-permission
metadata, since the OpenAPI document itself does not encode "dangerous" —
see `docs/plan/21-database-schema.md` §10.1).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
OPENAPI_SPEC_PATH = REPO_ROOT / "docs" / "plan" / "22-api-openapi.yaml"
SEED_PATH = REPO_ROOT / "services" / "api" / "candleviewer" / "auth" / "rbac_seed.json"
ENUM_OUT_PATH = (
    REPO_ROOT
    / "services"
    / "api"
    / "candleviewer"
    / "auth"
    / "generated_permissions.py"
)

#: Domain grouping used only for the enum's comment headers (cosmetic,
#: derived from each permission code's `domain` in `rbac_seed.json`) — kept
#: stable across regenerations by sorting on (domain, code) rather than
#: on file order, so the generated file's diff is minimal when a single
#: permission is added.
_DOMAIN_ORDER = (
    "admin",
    "accounts",
    "instruments",
    "marketdata",
    "recording",
    "replay",
    "trading",
    "rules",
    "alerts",
    "journal",
    "workspaces",
    "settings",
)


def load_openapi_spec(spec_path: Path = OPENAPI_SPEC_PATH) -> dict[str, Any]:
    with spec_path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)  # type: ignore[no-any-return]


def collect_permissions_from_spec(spec: dict[str, Any]) -> set[str]:
    """Every `x-rbac.permissions` entry across every operation in the spec."""
    codes: set[str] = set()
    for path_item in spec.get("paths", {}).values():
        if not isinstance(path_item, dict):
            continue
        for op in path_item.values():
            if not isinstance(op, dict):
                continue
            rbac = op.get("x-rbac")
            if not isinstance(rbac, dict):
                continue
            for code in rbac.get("permissions", []):
                codes.add(code)
    return codes


def collect_scopes_from_spec(spec: dict[str, Any]) -> set[str]:
    scopes: set[str] = set()
    for path_item in spec.get("paths", {}).values():
        if not isinstance(path_item, dict):
            continue
        for op in path_item.values():
            if not isinstance(op, dict):
                continue
            rbac = op.get("x-rbac")
            if not isinstance(rbac, dict):
                continue
            scope = rbac.get("scope")
            if scope is not None:
                scopes.add(scope)
    return scopes


def _member_name(code: str) -> str:
    domain, _, action = code.partition(":")
    return f"{domain.upper()}_{action.upper()}"


def render_enum(codes_by_domain: dict[str, list[str]]) -> str:
    lines = [
        '"""GENERATED by `tools/rbac/generate.py` from `docs/plan/22-api-openapi.yaml`',
        "`x-rbac.permissions` blocks — do not hand-edit (E09-T03).",
        "",
        "Regenerate with `python tools/rbac/generate.py`; CI's `generated-code`",
        "job runs `python tools/rbac/generate.py --check` and fails on drift.",
        "Mirrors `docs/plan/24-internal-schemas.md` §15.2 exactly (member",
        "order, values); `rbac_vocabulary_single_source` cross-checks this",
        "enum, the OpenAPI blocks and the database seed.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from enum import StrEnum",
        "",
        "",
        "class Permission(StrEnum):",
        '    """GENERATED from 22-api-openapi.yaml x-rbac.permissions - do not hand-edit."""',
        "",
    ]
    for domain in _DOMAIN_ORDER:
        codes = codes_by_domain.get(domain)
        if not codes:
            continue
        lines.append(f"    # {domain}")
        for code in sorted(codes):
            lines.append(f'    {_member_name(code)} = "{code}"')
        lines.append("")
    # Any domain not in the fixed cosmetic ordering still gets emitted, sorted,
    # so a new domain added to the OpenAPI document is never silently dropped.
    extra_domains = sorted(set(codes_by_domain) - set(_DOMAIN_ORDER))
    for domain in extra_domains:
        lines.append(f"    # {domain}")
        for code in sorted(codes_by_domain[domain]):
            lines.append(f'    {_member_name(code)} = "{code}"')
        lines.append("")

    lines.append("")
    lines.append("class Scope(StrEnum):")
    lines.append('    """The account dimension of the check; mirrors x-rbac.scope."""')
    lines.append("")
    lines.append('    NONE = "none"')
    lines.append('    SELF = "self"')
    lines.append('    GRANTED_ACCOUNTS = "granted_accounts"')
    lines.append("")
    return "\n".join(lines)


def _domain_for_code(code: str, seed_domains: dict[str, str]) -> str:
    return seed_domains.get(code, code.partition(":")[0])


def build_seed_permissions(
    spec_codes: set[str], existing_seed: dict[str, Any]
) -> list[dict[str, Any]]:
    """New permission list for `rbac_seed.json`: every code from the spec,
    preserving each existing entry's `domain`/`dangerous` metadata (which the
    OpenAPI document itself does not carry) and defaulting a brand-new code
    to its own `domain:action` domain segment and `dangerous=false` so a
    reviewer must explicitly flip it — never silently `true`."""
    existing_by_code = {p["code"]: p for p in existing_seed.get("permissions", [])}
    result: list[dict[str, Any]] = []
    for code in sorted(spec_codes):
        existing = existing_by_code.get(code)
        if existing is not None:
            result.append(
                {
                    "code": code,
                    "domain": existing["domain"],
                    "dangerous": existing["dangerous"],
                }
            )
        else:
            result.append(
                {"code": code, "domain": code.partition(":")[0], "dangerous": False}
            )
    return result


def render_seed(
    existing_seed: dict[str, Any], permissions: list[dict[str, Any]]
) -> str:
    new_seed = dict(existing_seed)
    new_seed["permissions"] = permissions
    return json.dumps(new_seed, indent=2, ensure_ascii=False) + "\n"


def render_outputs(
    spec_path: Path = OPENAPI_SPEC_PATH, seed_path: Path = SEED_PATH
) -> tuple[str, str]:
    """Pure: returns `(enum_content, seed_content)` for the given inputs.
    Never writes."""
    spec = load_openapi_spec(spec_path)
    spec_codes = collect_permissions_from_spec(spec)

    existing_seed: dict[str, Any] = {}
    if seed_path.exists():
        with seed_path.open(encoding="utf-8") as fh:
            existing_seed = json.load(fh)
    existing_domains = {
        p["code"]: p["domain"] for p in existing_seed.get("permissions", [])
    }

    codes_by_domain: dict[str, list[str]] = {}
    for code in spec_codes:
        domain = _domain_for_code(code, existing_domains)
        codes_by_domain.setdefault(domain, []).append(code)

    enum_content = render_enum(codes_by_domain)
    new_permissions = build_seed_permissions(spec_codes, existing_seed)
    seed_content = render_seed(existing_seed, new_permissions)
    return enum_content, seed_content


def _write_lf(path: Path, content: str) -> None:
    """Write with LF endings regardless of platform (`.gitattributes` says
    `eol=lf`; the default `newline=None` would emit CRLF on Windows)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    out_dir: Path | None = None
    if "--out-dir" in argv:
        out_dir = Path(argv[argv.index("--out-dir") + 1])

    enum_content, seed_content = render_outputs()

    changed = False
    if check_only:
        # Compare raw bytes (no newline translation) so a CRLF checkout is
        # reported as drift rather than silently normalised away.
        current_enum = (
            ENUM_OUT_PATH.read_bytes().decode("utf-8") if ENUM_OUT_PATH.exists() else ""
        )
        current_seed = (
            SEED_PATH.read_bytes().decode("utf-8") if SEED_PATH.exists() else ""
        )
        if current_enum != enum_content:
            print(f"DRIFT: {ENUM_OUT_PATH} is stale", file=sys.stderr)
            changed = True
        if current_seed != seed_content:
            print(f"DRIFT: {SEED_PATH} is stale", file=sys.stderr)
            changed = True
        return 1 if changed else 0

    enum_out = out_dir / ENUM_OUT_PATH.name if out_dir else ENUM_OUT_PATH
    seed_out = out_dir / SEED_PATH.name if out_dir else SEED_PATH
    _write_lf(enum_out, enum_content)
    _write_lf(seed_out, seed_content)
    print(f"wrote {enum_out}")
    print(f"wrote {seed_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
