"""GENERATED by `tools/rbac/generate.py` from `docs/plan/22-api-openapi.yaml`
`x-rbac.permissions` blocks — do not hand-edit (E09-T03).

Regenerate with `python tools/rbac/generate.py`; CI's `generated-code`
job runs `python tools/rbac/generate.py --check` and fails on drift.
Mirrors `docs/plan/24-internal-schemas.md` §15.2 exactly (member
order, values); `rbac_vocabulary_single_source` cross-checks this
enum, the OpenAPI blocks and the database seed.
"""

from __future__ import annotations

from enum import StrEnum


class Permission(StrEnum):
    """GENERATED from 22-api-openapi.yaml x-rbac.permissions - do not hand-edit."""

    # admin
    ADMIN_READ = "admin:read"
    AUDIT_EXPORT = "audit:export"
    AUDIT_READ = "audit:read"
    BACKUPS_READ = "backups:read"
    BACKUPS_WRITE = "backups:write"
    FLAGS_READ = "flags:read"
    FLAGS_WRITE = "flags:write"
    USERS_READ = "users:read"
    USERS_WRITE = "users:write"

    # accounts
    ACCOUNTS_READ = "accounts:read"
    ACCOUNTS_WRITE = "accounts:write"
    KEYS_MANAGE = "keys:manage"
    KEYS_READ = "keys:read"

    # instruments
    INSTRUMENTS_READ = "instruments:read"
    INSTRUMENTS_WRITE = "instruments:write"

    # marketdata
    MARKETDATA_READ = "marketdata:read"

    # recording
    RECORDING_READ = "recording:read"
    RECORDING_WRITE = "recording:write"

    # replay
    REPLAY_READ = "replay:read"
    REPLAY_WRITE = "replay:write"

    # trading
    EXECUTIONS_READ = "executions:read"
    KILLSWITCH_WRITE = "killswitch:write"
    ORDERS_READ = "orders:read"
    ORDERS_WRITE = "orders:write"
    POSITIONS_READ = "positions:read"
    POSITIONS_WRITE = "positions:write"

    # rules
    RULES_READ = "rules:read"
    RULES_WRITE = "rules:write"

    # alerts
    ALERTS_READ = "alerts:read"
    ALERTS_WRITE = "alerts:write"

    # journal
    JOURNAL_READ = "journal:read"
    JOURNAL_WRITE = "journal:write"

    # workspaces
    WORKSPACES_READ = "workspaces:read"
    WORKSPACES_WRITE = "workspaces:write"

    # settings
    SETTINGS_READ = "settings:read"
    SETTINGS_WRITE = "settings:write"


class Scope(StrEnum):
    """The account dimension of the check; mirrors x-rbac.scope."""

    NONE = "none"
    SELF = "self"
    GRANTED_ACCOUNTS = "granted_accounts"
