// GENERATED FILE - DO NOT EDIT BY HAND.
// Generator: tools/errorcodes/generate.py (E17-T05).
// Source: docs/plan/22-api-openapi.yaml (x-error-codes, x-error-codes-ws). Edit the YAML and run `make gen`.

export const ERROR_CODES = [
  "validation_failed",
  "unsupported_category",
  "tick_size_violation",
  "lot_size_violation",
  "invalid_cursor",
  "invalid_time_range",
  "unauthenticated",
  "mfa_required",
  "mfa_invalid",
  "refresh_token_invalid",
  "step_up_required",
  "session_read_only",
  "positions_unknown",
  "forbidden",
  "account_scope_denied",
  "trading_disabled",
  "risk_limit_breached",
  "not_found",
  "conflict",
  "idempotency_key_reuse",
  "idempotency_in_flight",
  "version_conflict",
  "gone",
  "order_not_amendable",
  "rule_ir_invalid",
  "insufficient_balance",
  "no_data_recorded",
  "rate_limited",
  "exchange_rate_limited",
  "internal_error",
  "exchange_error",
  "exchange_unavailable",
  "store_unavailable",
  "degraded_data",
  "timeout",
  "protocol_violation",
  "frame_malformed",
  "unsupported_protocol",
  "not_authenticated",
  "auth_failed",
  "auth_timeout",
  "token_expired",
  "unknown_topic",
  "invalid_topic_format",
  "unsupported_symbol",
  "invalid_options",
  "encoding_unsupported",
  "subscription_limit",
  "too_many_topics",
  "duplicate_subscription",
  "not_subscribed",
  "resync_rate_limited",
  "client_rate_limited",
  "slow_consumer",
  "replay_session_not_found",
  "replay_session_ended",
  "user_disabled",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ErrorMeta {
  readonly surfaces: readonly ("rest" | "ws")[];
  readonly scope: string | null;
  readonly retryable: boolean;
  readonly restAnalogue: ErrorCode | null;
  readonly closeCode: number | null;
}

export const ERROR_META: Readonly<Record<ErrorCode, ErrorMeta>> = {
  validation_failed: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  unsupported_category: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  tick_size_violation: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  lot_size_violation: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  invalid_cursor: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  invalid_time_range: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  unauthenticated: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  mfa_required: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  mfa_invalid: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  refresh_token_invalid: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  step_up_required: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  session_read_only: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  positions_unknown: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  forbidden: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  account_scope_denied: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  trading_disabled: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  risk_limit_breached: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  not_found: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  conflict: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  idempotency_key_reuse: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  idempotency_in_flight: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  version_conflict: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  gone: { surfaces: ["rest"], scope: null, retryable: false, restAnalogue: null, closeCode: null },
  order_not_amendable: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  rule_ir_invalid: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  insufficient_balance: {
    surfaces: ["rest"],
    scope: null,
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  no_data_recorded: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  rate_limited: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  exchange_rate_limited: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  internal_error: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  exchange_error: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  exchange_unavailable: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  store_unavailable: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  degraded_data: {
    surfaces: ["rest", "ws"],
    scope: "any",
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  timeout: {
    surfaces: ["rest"],
    scope: null,
    retryable: true,
    restAnalogue: null,
    closeCode: null,
  },
  protocol_violation: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: null,
    closeCode: 1002,
  },
  frame_malformed: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: null,
    closeCode: 1002,
  },
  unsupported_protocol: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: null,
    closeCode: 1002,
  },
  not_authenticated: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: "unauthenticated",
    closeCode: 4401,
  },
  auth_failed: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: "unauthenticated",
    closeCode: 4401,
  },
  auth_timeout: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: null,
    closeCode: 4401,
  },
  token_expired: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: true,
    restAnalogue: "unauthenticated",
    closeCode: 4401,
  },
  unknown_topic: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "not_found",
    closeCode: null,
  },
  invalid_topic_format: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "validation_failed",
    closeCode: null,
  },
  unsupported_symbol: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "unsupported_category",
    closeCode: null,
  },
  invalid_options: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "validation_failed",
    closeCode: null,
  },
  encoding_unsupported: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: null,
    closeCode: null,
  },
  subscription_limit: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: true,
    restAnalogue: "rate_limited",
    closeCode: null,
  },
  too_many_topics: {
    surfaces: ["ws"],
    scope: "request",
    retryable: true,
    restAnalogue: "rate_limited",
    closeCode: null,
  },
  duplicate_subscription: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "conflict",
    closeCode: null,
  },
  not_subscribed: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "not_found",
    closeCode: null,
  },
  resync_rate_limited: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: true,
    restAnalogue: "rate_limited",
    closeCode: null,
  },
  client_rate_limited: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: true,
    restAnalogue: "rate_limited",
    closeCode: 4429,
  },
  slow_consumer: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: true,
    restAnalogue: null,
    closeCode: 4429,
  },
  replay_session_not_found: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "not_found",
    closeCode: null,
  },
  replay_session_ended: {
    surfaces: ["ws"],
    scope: "topic",
    retryable: false,
    restAnalogue: "gone",
    closeCode: null,
  },
  user_disabled: {
    surfaces: ["ws"],
    scope: "connection",
    retryable: false,
    restAnalogue: "forbidden",
    closeCode: 4403,
  },
};

export const WS_ERROR_CODES: readonly ErrorCode[] = ERROR_CODES.filter((c) =>
  ERROR_META[c].surfaces.includes("ws"),
);
