"""tools/statechart/render_catalogue.py — E50-T01.

Regenerates the generated machine-index table in
`docs/plan/28-statechart-catalogue.md` from the machine-JSON contracts under
`services/api/candleviewer/statechart/machines/*.machine.json`, using the same
`candleviewer.statechart.registry` loader the runtime uses (so the table can
never drift from what the registry actually accepts).

Idempotent and deterministic: run twice, get byte-identical output. Wired
into `make gen`; CI additionally runs `git diff --exit-code` on the doc to
catch an un-regenerated table (see the Makefile `gen`/`gen-check` targets and
`tools/ci/check_gen_freshness.py`).

Usage:
    python tools/statechart/render_catalogue.py [--check]

`--check` renders to a temp buffer and exits non-zero on any diff against the
committed doc, without writing — used by `gen-check` style CI jobs that want
a single script rather than `render + git diff --exit-code`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_API_ROOT = _REPO_ROOT / "services" / "api"
_CATALOGUE = _REPO_ROOT / "docs" / "plan" / "28-statechart-catalogue.md"

_BEGIN = "<!-- BEGIN GENERATED: tools/statechart/render_catalogue.py -->"
_END = "<!-- END GENERATED: tools/statechart/render_catalogue.py -->"

_HEADER = (
    "## 25. Generated machine index\n\n"
    "> Regenerated by `tools/statechart/render_catalogue.py` from "
    "`services/api/candleviewer/statechart/machines/*.machine.json` via "
    "`candleviewer.statechart.registry`. Never hand-edit the table between the "
    "markers below — run `make gen` (or `python tools/statechart/render_catalogue.py`) "
    "instead; CI's `gen-check` job fails on drift.\n\n"
)


def _sys_path_for_api() -> None:
    api_str = str(_API_ROOT)
    if api_str not in sys.path:
        sys.path.insert(0, api_str)


def _render_table() -> str:
    _sys_path_for_api()
    from candleviewer.statechart.registry import Registry

    registry = Registry()
    keys = registry.keys()
    if not keys:
        return "_No machines registered yet under `statechart/machines/`._\n"

    lines = [
        "| Machine id | States (top-level) | `machine_hash` |",
        "|---|---|---|",
    ]
    for key in keys:
        chart = registry.get(key)
        states = chart.get("states")
        n_states = len(states) if isinstance(states, dict) else 0
        digest = registry.hash(key)
        lines.append(f"| `{key}` | {n_states} | `{digest[:12]}…` |")
    return "\n".join(lines) + "\n"


def render_section() -> str:
    return f"{_BEGIN}\n{_HEADER}{_render_table()}{_END}\n"


def _apply(doc: str, section: str) -> str:
    # `section` always ends in exactly one newline (from `render_section`);
    # trim it here so re-splicing into an existing doc never accumulates an
    # extra blank line each run (idempotency: run-twice must be a no-op).
    section = section[:-1] if section.endswith("\n") else section
    if _BEGIN in doc and _END in doc:
        pre, rest = doc.split(_BEGIN, 1)
        _, post = rest.split(_END, 1)
        return f"{pre}{section}{post}"
    # First run: append a new "## 25. Generated machine index" section at
    # end-of-file, separated from the preceding section by a horizontal rule
    # (matching the doc's existing `---` section-break convention). Always
    # leave the file ending in exactly one trailing newline.
    sep = "" if doc.endswith("\n\n") else ("\n" if doc.endswith("\n") else "\n\n")
    return f"{doc}{sep}---\n\n{section}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail with a diff-style message instead of writing, if the doc is stale.",
    )
    args = parser.parse_args(argv)

    # `newline=""` round-trips the doc's own CRLF line endings verbatim
    # (git stores this file CRLF) instead of normalising to LF, so a
    # no-op run never shows a line-ending-only diff.
    original = _CATALOGUE.open(encoding="utf-8", newline="").read()
    eol = "\r\n" if "\r\n" in original else "\n"
    section = render_section().replace("\n", eol)
    updated = _apply(original, section)

    if args.check:
        if updated != original:
            sys.stderr.write(
                f"{_CATALOGUE} is stale — run `python tools/statechart/render_catalogue.py`.\n"
            )
            return 1
        return 0

    if updated != original:
        with _CATALOGUE.open("w", encoding="utf-8", newline="") as fh:
            fh.write(updated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
