"""Render the committed cross-language artefacts for the bar model (E12-T01).

- `bar-model.schema.json` — JSON Schema of `BarSpec`/`Bar`/`BarUpdate`, the input for the
  generated TS mirror (`packages/protocol/scripts/generate-bar-types.mjs`).
- `spec_hash_vectors.json` — golden `spec_hash` vectors; any change in Python/pydantic that
  moves a hash fails `tests/unit/bars/test_spec_hash_golden.py`.

Both live under `packages/fixtures/golden/bars/` and are regenerated by
`scripts/generate_bar_artifacts.py` (`--check` diffs instead of writing).
"""

from __future__ import annotations

import json
from decimal import Decimal
from typing import Any

from pydantic.json_schema import models_json_schema

from candleviewer.bars.models import Bar, BarSpec, BarUpdate
from candleviewer.bars.spec import SPEC_HASH_VERSION, canonical_json, is_wire_representable, to_wire


def render_schema() -> str:
    _, doc = models_json_schema(
        [(BarSpec, "serialization"), (Bar, "serialization"), (BarUpdate, "serialization")],
        title="CandleViewer bar domain model (24-internal-schemas.md §3.1-§3.2)",
    )
    return json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def golden_specs() -> list[BarSpec]:
    """A fixed, never-reordered list: append only (vectors are positional)."""
    return [
        BarSpec(kind="time", interval_ms=60_000),
        BarSpec(kind="time", interval_ms=300_000),
        BarSpec(kind="time", interval_ms=86_400_000, session_anchor_utc_min=0),
        BarSpec(
            kind="time", interval_ms=3_600_000, session_anchor_utc_min=480, align_to_epoch=False
        ),
        BarSpec(kind="tick", tick_count=1000),
        BarSpec(kind="volume", volume_threshold=Decimal("50")),
        BarSpec(kind="volume", volume_threshold=Decimal("0.125")),
        BarSpec(kind="range", range_ticks=40),
        BarSpec(kind="delta", delta_threshold=Decimal("25")),
        BarSpec(kind="renko", range_ticks=30),
        BarSpec(kind="renko", range_ticks=30, renko_wick=True, reversal_bricks=3),
        BarSpec(kind="time", interval_ms=60_000, price_source="mark"),
    ]


def render_vectors() -> str:
    vectors: list[dict[str, Any]] = []
    for spec in golden_specs():
        entry: dict[str, Any] = {
            "canonical_json": canonical_json(spec),
            "spec_hash": spec.spec_hash,
        }
        if is_wire_representable(spec):
            bar_type, param = to_wire(spec)
            entry["wire"] = {"bar_type": bar_type, "param": param}
        vectors.append(entry)
    doc = {
        "$note": (
            "GENERATED - do not hand-edit. Regenerate with "
            "`python services/api/scripts/generate_bar_artifacts.py`. A diff here means "
            "every persisted bar/builder-state key moves: bump SPEC_HASH_VERSION + migrate."
        ),
        "spec_hash_version": SPEC_HASH_VERSION,
        "vectors": vectors,
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
