// Custom Style Dictionary format: `typescript/nested-object`.
//
// Produces `build/ts/tokens.ts` per docs/plan/16-design-system-brief.md
// §11: a typed `const tokens = {...} as const` nested object (dot-path
// token names become nested keys) plus a `TokenPath` union type, so
// component prop types can be statically checked against real token
// names (`tokens.color.buy.default`) and a typo'd token reference is a
// compile error rather than a silent CSS custom-property miss.

/**
 * @param {{ dictionary: { allTokens: Array<{ name: string, value: unknown }> } }} args
 */
export default function typescriptNestedObject({ dictionary }) {
  const root = {};
  const sorted = [...dictionary.allTokens].sort((a, b) => a.name.localeCompare(b.name));
  for (const token of sorted) {
    setPath(root, token.name.split("."), token.value);
  }

  const body = renderObject(root, 1);
  return [
    "/**",
    " * Do not edit directly — generated by `pnpm --filter @candleviewer/ui build:tokens`.",
    " * Source: packages/ui/tokens/*.tokens.json (docs/plan/16-design-system-brief.md #11).",
    " */",
    "",
    `export const tokens = {\n${body}\n} as const;`,
    "",
    "export type Tokens = typeof tokens;",
    "",
  ].join("\n");
}

function setPath(root, segments, value) {
  let node = root;
  for (let i = 0; i < segments.length - 1; i++) {
    const seg = segments[i];
    if (typeof node[seg] !== "object" || node[seg] === null || Array.isArray(node[seg])) {
      node[seg] = {};
    }
    node = node[seg];
  }
  node[segments[segments.length - 1]] = value;
}

function renderObject(node, depth) {
  const indent = "  ".repeat(depth);
  const keys = Object.keys(node).sort();
  const lines = keys.map((key) => {
    const value = node[key];
    const propKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
    if (value && typeof value === "object" && !Array.isArray(value)) {
      return `${indent}${propKey}: {\n${renderObject(value, depth + 1)}\n${indent}},`;
    }
    return `${indent}${propKey}: ${JSON.stringify(value)},`;
  });
  return lines.join("\n");
}
