#!/usr/bin/env python3
"""E17-T01: extract the WS JSON Schemas from ``23-ws-protocol.md`` (sections 13-15).

``23-ws-protocol.md`` section 16.5: the Markdown is the single source of truth;
every fenced ``json`` block in sections 13-15 is parsed strictly (no comments),
keyed by ``$id`` and bundled into ``packages/protocol/ws-schemas.json``. The
bundle is always regenerated, never hand-edited. Output is deterministic
(sorted keys, fixed formatting). Stdlib only; never ``eval``s anything.

Usage: ``python tools/contracts/extract_ws_schemas.py [--check]``
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
DEFAULT_MD = REPO / "docs" / "plan" / "23-ws-protocol.md"
DEFAULT_OUT = REPO / "packages" / "protocol" / "ws-schemas.json"

SECTION_START = re.compile(r"^## 13\.", re.MULTILINE)
SECTION_END = re.compile(r"^## 16\.", re.MULTILINE)
FENCE = re.compile(r"^```json[ \t]*\r?\n(.*?)\r?\n```[ \t]*$", re.MULTILINE | re.DOTALL)
COMMENT = (
    "GENERATED by tools/contracts/extract_ws_schemas.py from docs/plan/23-ws-protocol.md "
    "sections 13-15. Do not hand-edit: edit the Markdown and run `make gen`."
)


class ExtractError(Exception):
    """Raised for any malformed, duplicate or unkeyed schema block."""


def schema_section(markdown: str) -> str:
    start = SECTION_START.search(markdown)
    end = SECTION_END.search(markdown)
    if start is None or end is None or end.start() <= start.start():
        raise ExtractError("could not locate sections 13-15 (headings '## 13.' .. '## 16.')")
    return markdown[start.start() : end.start()]


def extract_schemas(markdown: str) -> dict[str, dict[str, Any]]:
    """Return ``{$id: schema}`` for every fenced json block in sections 13-15."""
    section = schema_section(markdown)
    schemas: dict[str, dict[str, Any]] = {}
    for match in FENCE.finditer(section):
        line = section.count("\n", 0, match.start()) + 1
        try:
            block = json.loads(match.group(1))
        except json.JSONDecodeError as exc:
            raise ExtractError(
                f"json block at section-13-15 line {line} is not valid JSON "
                f"(comments are not allowed here): {exc}"
            ) from exc
        if not isinstance(block, dict) or not isinstance(block.get("$id"), str):
            raise ExtractError(f"json block at section-13-15 line {line} has no string $id")
        sid = block["$id"]
        if sid in schemas:
            raise ExtractError(f"duplicate $id {sid!r} (block at section-13-15 line {line})")
        schemas[sid] = block
    if not schemas:
        raise ExtractError("extracted zero schemas - the parser or the document is broken")
    return schemas


def build_bundle(markdown: str) -> dict[str, Any]:
    schemas = extract_schemas(markdown)
    return {
        "$comment": COMMENT,
        "source": "docs/plan/23-ws-protocol.md",
        "schemaCount": len(schemas),
        "schemas": dict(sorted(schemas.items())),
    }


def serialize(bundle: dict[str, Any]) -> str:
    return json.dumps(bundle, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--md", type=Path, default=DEFAULT_MD)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="fail if the bundle is stale")
    args = ap.parse_args(argv)
    try:
        text = serialize(build_bundle(args.md.read_text(encoding="utf-8")))
    except ExtractError as exc:
        print(f"[extract_ws_schemas] ERROR: {exc}", file=sys.stderr)
        return 1
    count = json.loads(text)["schemaCount"]
    if args.check:
        current = args.out.read_bytes().decode("utf-8") if args.out.exists() else ""
        if current != text:
            print(f"[extract_ws_schemas] {args.out} is stale; run `make gen`.", file=sys.stderr)
            return 1
        print(f"[extract_ws_schemas] OK - {count} schemas, bundle up to date")
        return 0
    args.out.write_bytes(text.encode("utf-8"))
    print(f"[extract_ws_schemas] wrote {args.out} ({count} schemas)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
