# -----------------------------------------------------------------------------
# bench_c_timers.py — (c) `after` / delay precision at 10 ms, 100 ms, 1 s
# -----------------------------------------------------------------------------
"""How accurate are `after` transitions, idle and under CPU/event load?

For each target delay we start M machines that do nothing but wait on
`after: {D: "fired"}`, and record (actual_fire_time - expected_fire_time).

Load is generated by a configurable number of *busy* interpreters churning
OMS events on the same event loop, plus optionally a CPU hog coroutine.

⚠️ Windows note: the default asyncio event loop on Windows has a timer
resolution around 15.6 ms unless the system timer is raised. Numbers below
10 ms must be read with that in mind — this is a platform property, not
purely a library property. Recorded so CandleViewer does not design a
10 ms control loop on top of it.
"""

from __future__ import annotations

import asyncio
import time
from typing import Any, Dict, List

import common
from xstate_statemachine import Interpreter, MachineLogic, create_machine

TIMER_SAMPLES = 60


def timer_machine(delay_ms: int) -> Any:
    config = {
        "id": f"t{delay_ms}",
        "initial": "waiting",
        "context": {"fired_at": 0.0},
        "states": {
            "waiting": {"after": {delay_ms: {"target": "fired"}}},
            "fired": {"entry": ["stamp"], "type": "final"},
        },
    }

    def stamp(i: Any, ctx: Dict[str, Any], e: Any, a: Any) -> None:
        ctx["fired_at"] = time.perf_counter()

    return create_machine(config, logic=MachineLogic(actions={"stamp": stamp}))


async def measure(delay_ms: int, samples: int) -> List[float]:
    """Returns per-sample error in milliseconds (actual - expected)."""
    errs: List[float] = []
    # ⏳ sequential: each timer measured on its own so queuing effects of
    #    N simultaneous timers don't hide inside one aggregate number.
    for _ in range(samples):
        interp = Interpreter(timer_machine(delay_ms))
        t0 = time.perf_counter()
        await interp.start()
        deadline = t0 + delay_ms / 1000.0 + 5.0
        while interp.context["fired_at"] == 0.0:
            if time.perf_counter() > deadline:
                break
            await asyncio.sleep(0.0005)
        fired = interp.context["fired_at"]
        await interp.stop()
        if fired:
            errs.append(((fired - t0) - delay_ms / 1000.0) * 1000.0)
    return errs


async def busy_load(n_busy: int, stop: asyncio.Event) -> List[Any]:
    """Spin up `n_busy` interpreters continuously chewing OMS events."""
    interps = [Interpreter(common.oms_machine()) for _ in range(n_busy)]
    await asyncio.gather(*(i.start() for i in interps))
    cycle = common.oms_event_cycle(20)

    async def churn(i: Any) -> None:
        while not stop.is_set():
            for e in cycle:
                if stop.is_set():
                    return
                await i.send(e)
            await asyncio.sleep(0)

    tasks = [asyncio.create_task(churn(i)) for i in interps]
    return [interps, tasks]


async def cpu_hog(stop: asyncio.Event) -> None:
    """A coroutine that blocks the loop in ~2 ms chunks — models a bar build."""
    while not stop.is_set():
        t_end = time.perf_counter() + 0.002
        while time.perf_counter() < t_end:
            pass
        await asyncio.sleep(0)


async def scenario(
    name: str, n_busy: int, hogs: int, delays=(10, 100, 1000)
) -> Dict[str, Any]:
    stop = asyncio.Event()
    interps: List[Any] = []
    tasks: List[Any] = []
    if n_busy:
        interps, tasks = await busy_load(n_busy, stop)
    for _ in range(hogs):
        tasks.append(asyncio.create_task(cpu_hog(stop)))

    out: Dict[str, Any] = {"scenario": name, "busy_interpreters": n_busy,
                           "cpu_hogs": hogs}
    for d in delays:
        # fewer samples for the 1 s timer (it would take a minute otherwise)
        s = TIMER_SAMPLES if d < 1000 else 15
        errs = await measure(d, s)
        out[f"after_{d}ms_error_ms"] = common.summarize(errs)
        out[f"after_{d}ms_error_ms"]["min"] = min(errs) if errs else None

    stop.set()
    for t in tasks:
        t.cancel()
    await asyncio.gather(*tasks, return_exceptions=True)
    if interps:
        await asyncio.gather(*(i.stop() for i in interps))
    return out


async def main() -> None:
    common.report("machine_specs", common.machine_specs())
    res: Dict[str, Any] = {}
    res["idle"] = await scenario("idle", 0, 0)
    res["load_100_interpreters"] = await scenario("load_100", 100, 0)
    res["load_500_interpreters"] = await scenario("load_500", 500, 0)
    res["load_500_plus_cpu_hog"] = await scenario("load_500_hog", 500, 2)
    common.report("c_timer_precision", res)


if __name__ == "__main__":
    asyncio.run(main())
