# -*- coding: utf-8 -*-
from _e38_gen import t, body, MS, PH, AREA, DOD_COMMON, DOD_UI

ST = dict(kind="Story", phase=PH, milestone=MS, perspective="Development", parent="E38")

t(**ST, key="E38-S06", component="web", title="Reset a paper balance safely and never in live",
  labels=["type/feature", AREA, "priority/p1", "a11y", "design-qa", "security"], sprint="Sprint 19",
  priority="P1 High", risk="R15 Data lifecycle", estimate=2, blocked_by=["E38-D06", "E38-S03", "E38-S01"],
  body=body(
   ctx="US-PAPER-006 (Should) lets a trader start a clean practice run. Two of its three scenarios are safety requirements rather than features: open positions must be warned about and explicitly confirmed as discarded, and **the reset control is unavailable in Live and hidden entirely, not merely disabled**. Its NFR adds that reset never touches live data and that each reset starts a new paper session id used by analytics.\n\nThe control lives on SCR-079 (Account detail drawer, trading side) per `docs/plan/18-traceability-matrix.md`.",
   scope="- Backend: `POST /exchange-accounts/{accountId}/paper-reset` (new endpoint; add to `docs/plan/22-api-openapi.yaml` with `x-idempotency: required` and `x-rbac` permissions `accounts:write`, scope `granted_accounts`), taking a starting balance and requiring the account to be a paper/demo-bound account.\n- Reset semantics, executed in one transaction: cancel and clear simulated resting orders in the matcher, close and clear simulated positions, set the `PaperLedger` wallet to the chosen starting balance, allocate a **new paper session id**, and write a reset record into the paper journal plus an audit row.\n- Hard refusal if the target account's `env` is `live` or the account is not paper-capable - returning 403 and auditing the attempt at high severity (this is a data-destruction path pointed at the wrong account type).\n- Frontend on **SCR-079**: the reset control with a starting-balance input validated against the instrument/account constraints; a warning naming the exact count of open simulated positions and resting orders that will be discarded; an explicit confirmation (CMP-044 ConfirmDialog, variant per E38-D06); and **complete absence of the control when the environment is live** - not a disabled control.\n- Analytics: the new paper session id partitions results so a fresh run is not blended with the previous one; surfaced in the journal filter.",
   oos="- Resetting a Bybit demo account's real balance at the exchange (not possible through the API; only the local paper ledger is reset - state this in the UI copy).\n- The matcher itself (E38-S03).\n- Journal analytics grouping beyond exposing the session id (E41).",
   ac="```gherkin\nScenario: Reset clears state and sets the balance\n  Given a paper account with simulated positions and resting orders\n  When the user resets with a chosen starting balance\n  Then positions and orders are cleared, the balance is set, a new paper session id is allocated, and the reset is recorded in the paper journal\n\nScenario: Open positions require explicit confirmation\n  Given open paper positions exist\n  When the user initiates a reset\n  Then a warning names the exact number of positions and orders to be discarded and the reset proceeds only after explicit confirmation\n\nScenario: The control is hidden, not disabled, in live\n  Given the session environment is live\n  When the account drawer renders\n  Then the reset control is absent from the DOM entirely, and a test asserts no disabled reset control exists\n\nScenario: Reset never touches live data\n  Given a live account id is submitted to the reset endpoint\n  When the request is processed\n  Then it is refused with 403, no live row is modified, and the attempt is audited at high severity\n\nScenario: Reset is atomic\n  Given a failure occurs partway through clearing state\n  When the transaction aborts\n  Then no partial reset is visible: balance, positions and orders are all as they were before\n\nScenario: Analytics separate the runs\n  Given two paper sessions separated by a reset\n  When journal analytics are viewed\n  Then results are attributable to each session id and are not blended by default\n```",
   tech="- The endpoint is idempotency-keyed so a retried request after a network blip does not double-reset into a second session id.\n- The reset runs inside a Postgres transaction covering the ledger, positions, orders and journal rows; the in-memory matcher state is rebuilt from the committed state afterwards, so a crash between commit and rebuild recovers correctly rather than leaving ghosts.\n- The 'hidden in live' requirement is enforced by conditional rendering at the container level plus a unit test asserting absence - a CSS-hidden control would satisfy neither the story nor a screen-reader user.\n- Copy must state plainly that this resets the **local paper ledger**, not any exchange-side demo balance, so the user is not misled about what changed.",
   test="- Unit: refusal matrix over account env and paper-capability.\n- Unit: atomicity - inject a failure after positions are cleared and assert full rollback.\n- Unit: idempotent retry yields one reset and one session id.\n- Unit (frontend): the control is absent in live; present in demo; the warning renders exact counts.\n- Contract: the new endpoint against the OpenAPI document; error registry entry for the refusal code.\n- Integration: reset with open positions, then verify matcher state, ledger, journal record and audit row.\n- axe-core on the drawer with the confirmation open.\n- E2E (feeds E38-Q02): reset from the UI and confirm analytics partition by session id.\n- Coverage: >=85% backend, >=80% frontend.",
   sec="- This is a destructive data operation. Threats: wrong-target destruction (live account), unauthorised destruction (a manager resetting an account they merely view), repudiation.\n- Controls: server-side env/paper-capability check, `accounts:write` on granted accounts only, explicit confirmation, idempotency, high-severity audit of both successes and refused attempts.\n- Data classification: financial simulation data; destruction is irreversible, so the journal reset record is the only recovery trail and must be written before the clear commits.\n- `security` label applied per `docs/plan/02-definition-of-ready-done.md` section 8 (touches account-scoped state).",
   a11y="- The confirmation dialog is labelled by its heading, traps focus, does not default focus to the destructive button, and announces the counts of what will be discarded.\n- The starting-balance field has a visible label, an accessible error message on invalid input, and is not validated by colour alone.\n- Absence-in-live is the accessible behaviour: a disabled control would be announced and confuse; the design explicitly requires removal.",
   perf="- Reset is a small transactional operation on a single account; it must complete within budget #13 (write endpoints <300 ms p95 backend-internal). Clearing a large number of resting simulated orders should be a set operation, not a per-order loop.",
   obs="- Audit `paper.balance_reset` with account, previous balance, new balance, discarded position and order counts, and the new session id; audit `paper.balance_reset_refused` with the reason.\n- Metric `cv_paper_resets_total{outcome}`.",
   dod=DOD_UI,
   deps="- `blocked_by: E38-D06` (SCR-079 reset design and copy), `E38-S03` (the `PaperLedger` and matcher state being reset), `E38-S01` (paper-capable account routing established).\n- SCR-079's shell is owned by E27/E28 - land this as a section inside it, not a new screen.",
   branch="`feat/e38-paper-reset`; PR size: ~250 LOC across backend and frontend.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-006\n- `docs/plan/14-screens-catalogue.md` SCR-079\n- `docs/plan/15-component-catalogue.md` CMP-044, CMP-116, CMP-128, CMP-129\n- `docs/plan/22-api-openapi.yaml` (new endpoint), `docs/plan/21-database-schema.md` paper ledger tables"))

t(**ST, key="E38-S07", component="auth", title="Grant, revoke and acknowledge per-user demo and live eligibility",
  labels=["type/feature", AREA, "priority/p1", "security", "a11y", "design-qa"], sprint="Sprint 19",
  priority="P1 High", risk="R9 Advice boundary", estimate=2, blocked_by=["E38-D06", "E38-T02", "E09", "E42"],
  body=body(
   ctx="US-PAPER-007 (Should) lets the owner control who may use demo and live so new managers start safely. Its NFR is precise: 'eligibility is a server-side attribute of the user-account binding'. That binding already exists as `user_account_access` (`docs/plan/21-database-schema.md` section 3.1.3), and the session already exposes `allowed_environments` (`docs/plan/22-api-openapi.yaml` `SessionInfo`, `docs/plan/23-ws-protocol.md` `auth_ok`).\n\nThe hardest requirement is revocation while positions are open: existing positions must remain manageable in **reduce-only** mode while new entries are refused - a graceful degradation, not a hard cut that would trap a manager in a position they cannot close.",
   scope="- Persist live eligibility as a server-side attribute of the user-account binding: extend `user_account_access` (migration) with `live_enabled boolean NOT NULL DEFAULT false` and `live_enabled_acknowledged_at timestamptz`, and derive `allowed_environments` for a session from the union over the user's granted accounts, intersected with the `live_trading` flag.\n- Grant and revoke through the existing `PUT /users/{userId}/account-access` surface, extending `AccountAccessGrantInput` with the eligibility field; changes are audited and take effect on the next request, with existing WS subscriptions for revoked scope force-closed with an `unsubscribed` frame (the behaviour already documented for that endpoint).\n- **Acknowledgement on promotion**: when live access is granted, the user must acknowledge the change at next sign-in before any live-targeting action is permitted; the acknowledgement is recorded and audited.\n- **Revocation with open positions**: when live access is revoked while the user holds live positions, their session enters reduce-only for those accounts - amend/cancel/close are permitted, position-opening is refused with a clear reason - until the positions are flat.\n- Frontend on **SCR-122 Admin: user detail / edit**: the eligibility control, the current-state display, the reason surfaced to a demo-only manager on SCR-074 ('The owner hasn't enabled Live for your account.'), the acknowledgement prompt at sign-in, and the reduce-only banner state.\n- Wire `allowed_environments` into E38-T02's isolation check so eligibility is enforced at the same choke point rather than in a second place.",
   oos="- Role and permission administration generally (E42 owns SCR-122's structure and the RBAC matrix).\n- The `live_trading` global flag (E42) and the R4 live-enablement gate (E44).\n- Reduce-only enforcement mechanics in the OMS (E29/E39 own the reduce-only order path; this story sets the flag that turns it on for a user-account pair).",
   ac="```gherkin\nScenario: A demo-only manager cannot select live\n  Given a manager whose grants include no live-enabled account\n  When they open the environment switcher\n  Then no live account is selectable and the Live switch is disabled with the reason shown\n\nScenario: Promotion requires acknowledgement\n  Given the owner grants live access to a manager\n  When that manager next signs in\n  Then they must acknowledge the change before any live-targeting action is permitted, and both the grant and the acknowledgement are audited\n\nScenario: Revocation with open positions degrades to reduce-only\n  Given a manager holds live positions\n  When the owner revokes their live access\n  Then existing positions remain manageable in reduce-only mode while new entries are refused with a stated reason\n\nScenario: Revocation with no open positions is immediate\n  Given a manager holds no live positions\n  When live access is revoked\n  Then live-targeting requests are refused with 403 from the next request, and live subscriptions are force-closed\n\nScenario: Eligibility is enforced server-side, not in the UI\n  Given a manager without live eligibility\n  When a crafted live-targeting request is sent directly to the API\n  Then it is refused with 403 and audited, independently of what the UI offered\n\nScenario: A manager cannot self-grant\n  Given a manager with accounts:write on their own grants\n  When they attempt to set live eligibility on themselves\n  Then the request is refused: eligibility changes require the owner's users:write permission\n```",
   tech="- Reuse the existing account-access endpoint rather than inventing an eligibility endpoint - the story's NFR explicitly places eligibility on the user-account binding, and a second surface would split the decision across two places (the same reasoning `docs/plan/21-database-schema.md` gives for rejecting a `rules:arm_live` permission).\n- Session `allowed_environments` derivation is cached per session and invalidated on grant change; the force-close of revoked subscriptions is the existing mechanism from `docs/plan/23-ws-protocol.md` section 9.\n- Reduce-only is expressed as a per-(user, account) flag consumed by the OMS's existing reduce-only path; it is set at revocation and cleared automatically when the account's live positions reach flat.\n- Acknowledgement is a row, not a client-side dismissal: the API refuses live actions while `live_enabled_acknowledged_at` is null for a currently-granted account.\n- Migration is additive with a safe default (`false`), so no existing user silently gains live access.",
   test="- Unit: `allowed_environments` derivation over grant combinations, incl. the `live_trading` flag being off.\n- Unit: self-grant refusal; owner-only enforcement.\n- Unit: acknowledgement gate blocks live actions until recorded.\n- Unit: reduce-only flag set on revocation with open positions, cleared on flat.\n- Contract: extended `AccountAccessGrantInput`/`AccountAccessGrant` schemas; session `allowed_environments`; `auth_ok` frame.\n- Integration: revoke while positions are open, then assert close succeeds and open is refused; assert WS force-close on revoked scope.\n- Migration test: default `false` for all existing rows; rollback tested.\n- E2E (feeds E38-Q02): owner grants, manager acknowledges at sign-in, manager switches to live; then owner revokes and the manager sees reduce-only.\n- Coverage: >=90% on the eligibility derivation module.",
   sec="- This is a privilege-management surface: threats are elevation of privilege (self-grant, forged grant), bypass (acting on a grant before acknowledgement), and trapping a user in an unmanageable position (availability harm) - the reduce-only design addresses the last.\n- Controls: owner-only `users:write` for eligibility, audited grant/revoke/acknowledge, enforcement at E38-T02's single choke point, additive migration defaulting to no access.\n- The reason shown to a demo-only manager must not disclose other users' grants.\n- `security` label mandatory (`docs/plan/02-definition-of-ready-done.md` section 8: anything touching RBAC). Abuse cases are exercised in E38-X02.",
   a11y="- The eligibility control on SCR-122 has a clear current-state label and an accessible confirmation for a change that affects another person's capabilities.\n- The acknowledgement prompt at sign-in is a focused, keyboard-operable dialog that cannot be dismissed by clicking away, with its consequences stated in text.\n- The reduce-only banner uses the disabled-with-reason pattern so the reason is programmatically associated with the blocked controls.",
   perf="- Eligibility resolution is per-request but cache-backed; it must not add a query per request. Assert p95 added latency <2 ms, consistent with E38-T02's budget.",
   obs="- Audit `user.live_access_granted`, `user.live_access_revoked`, `user.live_access_acknowledged`, each with actor, subject, account and timestamp.\n- Metric `cv_live_eligible_users` gauge, visible on the admin security centre - an unexpected increase is a security signal.\n- Log reduce-only activations and their automatic clearance.",
   dod=DOD_UI,
   deps="- `blocked_by: E38-D06` (SCR-122 eligibility design and copy), `E38-T02` (the choke point that enforces it), `E09` (sessions, RBAC, sign-in flow for the acknowledgement), `E42` (SCR-122 screen shell and the audit browser).",
   branch="`feat/e38-live-eligibility`; PR size: split into (1) migration + derivation + enforcement, (2) admin UI + acknowledgement.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-007\n- `docs/plan/21-database-schema.md` section 3.1.3 `user_account_access`\n- `docs/plan/22-api-openapi.yaml` `PUT /users/{userId}/account-access`, `SessionInfo.allowed_environments`\n- `docs/plan/23-ws-protocol.md` `auth_ok`, section 9 force-close\n- `docs/plan/14-screens-catalogue.md` SCR-122, SCR-074"))

t(**ST, key="E38-S08", component="web", title="Generate and display the demo-versus-live parity report with staleness flags",
  labels=["type/feature", AREA, "priority/p1", "a11y", "design-qa"], sprint="Sprint 19",
  priority="P1 High", risk="R6 Feed rot", estimate=2, blocked_by=["E38-D06", "E38-K01", "E38-T01", "E42"],
  body=body(
   ctx="US-PAPER-008 (Should) gives the owner a report of known demo-versus-live differences so expectations are calibrated, and it is the artefact that makes R4 'a gating exercise rather than a re-architecture' (roadmap section 7.1 goal 5). Its NFR forbids the easy implementation: 'the report is generated from a maintained data file plus runtime observations, never hand-written prose only'.\n\nThree behaviours define it: list the known differences with their source and last-verified date; capture operations that fail only in demo as **candidate** parity items; and flag items unverified for 90 days as needing re-verification. The report lives in SCR-137 (Admin: security centre) and is linked from SCR-074.",
   scope="- Backend: load `packages/backend/cv/paper/parity_items.yaml` (seeded by E38-K01) at startup, validate it against a schema (id, area, description, source, severity, last_verified, capability_ref), and expose it via a new `GET /admin/parity` endpoint (add to `docs/plan/22-api-openapi.yaml`, `x-rbac` permission `audit:read`, scope none).\n- **Runtime observation capture**: every `CapabilityUnsupported` refusal (E38-T01) and every demo-only exchange error observed by the adapter is recorded as a *candidate* parity item with its operation, error signature, first-seen and last-seen timestamps and an occurrence count - deduplicated by signature, never auto-promoted into the confirmed list.\n- **Staleness**: any confirmed item whose `last_verified` is older than 90 days is returned flagged `needs_reverification`; a scheduled job recomputes the flag daily and raises a notification when an item crosses the threshold.\n- Re-verification action: an owner-only endpoint marking an item verified (updating `last_verified` and writing an audit row), intended to be driven by re-running the E38-K01 probe harness.\n- Frontend on **SCR-137**: the parity table (difference, area, source, last verified, status), the needs-re-verification treatment using text plus icon, the candidate-items inbox with promote/dismiss actions, and empty/loading/error/RBAC-denied states. Components CMP-028, CMP-036, CMP-050, CMP-087, CMP-093, CMP-175, CMP-178.\n- A link from SCR-074 to the report, so a user hitting a demo limitation can read why.\n- Deep-link support: a `CapabilityUnsupported` refusal carries `parity_item_id`, and the UI links the refusal message to that row.",
   oos="- The probe harness that produces verification evidence (E38-K01 built it; this story only records the outcome).\n- The paper-fidelity divergence panel (E38-T03 produces the data; its display reuses this screen's patterns but is a separate concern).\n- Auto-promoting candidates to confirmed items - deliberately a human decision.",
   ac="```gherkin\nScenario: The report lists known differences with source and date\n  Given the seeded parity data file\n  When the report is requested\n  Then each known difference is listed with its description, source and last-verified date, including no-WS-order-entry-in-demo, batch-order category limits and fee differences\n\nScenario: A demo-only failure becomes a candidate item\n  Given an operation fails only in demo\n  When the failure is observed at runtime\n  Then it is recorded as a candidate parity item with its error signature and occurrence count, and is not silently merged into the confirmed list\n\nScenario: Stale items are flagged\n  Given an item last verified 91 days ago\n  When the report is generated\n  Then that item is flagged as needing re-verification and a notification is raised once, not on every generation\n\nScenario: The report is generated, not authored\n  Given the parity data file is modified\n  When the report is requested\n  Then the output reflects the file without any code change, and a test asserts no report content is hardcoded in the UI\n\nScenario: An invalid data file fails loudly at startup\n  Given a parity item missing a required field\n  When the application starts\n  Then startup fails with a precise validation error rather than serving a silently incomplete report\n\nScenario: A refusal links to its parity item\n  Given a capability refusal carrying a parity item id\n  When the user follows the link\n  Then the parity report opens focused on that row\n\nScenario: Re-verification is audited\n  Given the owner marks an item verified\n  When the change is saved\n  Then last_verified updates and an audit row records who verified it and when\n```",
   tech="- The data file is the source of truth and is version-controlled; the DB holds only runtime observations and verification timestamps, joined at read time. This keeps the curated knowledge reviewable in PRs while the observed knowledge accumulates at runtime.\n- Candidate deduplication key: (operation, retCode, normalised retMsg) - normalise out ids and timestamps so one real difference is not recorded as thousands of candidates.\n- The staleness notification uses the existing notification/alert delivery path rather than a bespoke mechanism.\n- `capability_ref` cross-links each item to an `EnvironmentCapabilities` field, and a test asserts every hard capability restriction has a parity item and vice versa - this is what prevents the code and the report drifting apart.\n- The UI renders whatever the API returns, including item types it does not know about, so adding a parity item never requires a frontend release.",
   test="- Unit: schema validation of the data file, incl. the startup-failure case.\n- Unit: staleness computation at the 89/90/91-day boundaries.\n- Unit: candidate deduplication and occurrence counting under repeated identical failures.\n- Unit: capability-to-parity-item bidirectional coverage test.\n- Contract: `GET /admin/parity` and the verification endpoint against OpenAPI; RBAC denial for non-`audit:read` callers.\n- Integration: trigger a capability refusal through the adapter and assert a candidate item appears with the right signature.\n- axe-core on the SCR-137 parity section incl. the flagged state.\n- E2E (feeds E38-Q02): open the report, follow a deep link from a refusal, mark an item verified and observe the audit row.\n- Coverage: >=85% backend, >=80% frontend.",
   sec="- SCR-137 is the security centre: the report must contain no key material, no account identifiers beyond what the caller may already see, and no raw exchange responses that might embed credentials - candidate items store a normalised signature, not the raw payload.\n- Access requires `audit:read`; verification requires owner-level permission and is audited.\n- Threat: a stale or wrong parity report giving false confidence before R4 live enablement - mitigated by the staleness flag and the capability cross-link test.\n- Data classification: operational/security metadata, internal.",
   a11y="- Real table semantics with header associations; needs-re-verification and candidate states use text plus icon, never colour alone.\n- The candidate inbox's promote/dismiss actions have accessible names naming the item.\n- Deep-linked rows receive focus and are announced on arrival.\n- Empty state explains what would populate the table rather than showing a bare 'no data'.",
   perf="- Tens of rows: no virtualisation needed. The report is assembled from an in-memory data file plus one indexed query; target <150 ms p95 (budget #13 read endpoints).\n- Candidate recording must be fire-and-forget on the refusal path so it cannot add latency to an order rejection.",
   obs="- Metric `cv_parity_items{status}` gauge (confirmed, candidate, stale).\n- Audit `parity.item_verified`, `parity.candidate_promoted`, `parity.candidate_dismissed`.\n- Notification when an item becomes stale, delivered once per transition.",
   dod=DOD_UI,
   deps="- `blocked_by: E38-K01` (the seeded data file and ADR-0016), `E38-T01` (capability refusals are the runtime observation source and the cross-link target), `E38-D06` (SCR-137 design), `E42` (SCR-137 screen shell, audit browser and notification plumbing).",
   branch="`feat/e38-parity-report`; PR size: split into (1) data file loading + API + observation capture, (2) SCR-137 UI.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-008\n- `docs/plan/14-screens-catalogue.md` SCR-137, SCR-074\n- `docs/plan/04-security-program.md` SR-040a\n- `docs/plan/27-adrs/ADR-0016-demo-live-parity.md` (produced by E38-K01)\n- `docs/plan/15-component-catalogue.md` CMP-028, CMP-036, CMP-050, CMP-087, CMP-093, CMP-175, CMP-178"))

t(**dict(kind="Task", component="backtesting", phase=PH, milestone=MS, perspective="Development", parent="E38"),
  key="E38-T03", title="Nightly paper-versus-demo fill divergence job and fidelity panel data",
  labels=["type/tech", AREA, "priority/p2", "perf"], sprint="Sprint 19",
  priority="P2 Medium", risk="R12 Backtest bias", estimate=2, blocked_by=["E38-S03", "E38-S01", "E26"],
  body=body(
   ctx="`docs/plan/24-internal-schemas.md` section 12.5 states the requirement plainly: 'The paper matcher's honesty is verified, not assumed.' A nightly job replays a recorded day through the matcher while comparing against the demo account's real fills for the same period where they overlap, reporting mean and p95 slippage difference, fill-rate difference for resting limits and fee difference. A p95 slippage divergence above one tick or a fill-rate divergence above 10 pp opens a defect ticket against the fill model, and results are shown on the admin 'Paper fidelity' panel.\n\nWithout this job, US-PAPER-004's simulator is an unfalsifiable claim, and R12 (backtest bias) has no control at all.",
   scope="- Scheduled job in `packages/backend/cv/paper/divergence.py`: for each symbol with both recorded market data and real demo fills in the window, replay the recorded day through the `PaperMatcher` using the same order stream the demo account actually submitted, and compare outcomes.\n- Metrics computed per symbol and overall: mean and p95 slippage difference (in ticks), fill-rate difference for resting limit orders (percentage points), fee difference, and count of orders compared.\n- Threshold evaluation: p95 slippage divergence >1 tick or fill-rate divergence >10 pp raises a defect - emit an alert and create a tracked issue record (not silently logged).\n- Persist results as a dated document queryable by the admin fidelity panel; expose via `GET /admin/paper-fidelity` (add to `docs/plan/22-api-openapi.yaml`, `x-rbac` permission `audit:read`).\n- Handle the honest edge cases: no overlap (report 'insufficient data', never a fabricated zero divergence), too few comparable orders for a meaningful p95 (report the sample size and suppress the threshold check), and symbols where recording gaps make the replay unfaithful (detect via `GET /market/data-coverage` and exclude with a stated reason).\n- Update `docs/plan/24-internal-schemas.md` section 12.5 and `docs/plan/20-architecture.md` section 3.7 if the implemented metric definitions differ from the written ones, and record any fill-model decision made during implementation as an ADR amendment.",
   oos="- The fidelity panel UI beyond the API (its design is E38-D03; the rendering is folded into E38-S08's SCR-137 patterns or filed as a follow-up if capacity is short).\n- Automatically tuning the fill model from divergence results - tuning is a human decision informed by the report.\n- Comparing against *live* fills (there are none in R3).",
   ac="```gherkin\nScenario: Divergence is computed over overlapping activity\n  Given a recorded day with both market data and real demo fills\n  When the nightly job runs\n  Then mean and p95 slippage difference, resting-limit fill-rate difference and fee difference are computed and persisted with the compared-order count\n\nScenario: Breaching a threshold raises a defect\n  Given a p95 slippage divergence above one tick\n  When the job evaluates thresholds\n  Then an alert is raised and a tracked defect record is created against the fill model, not merely logged\n\nScenario: Insufficient data is reported, not fabricated\n  Given a day with no overlapping demo fills\n  When the job runs\n  Then the result states insufficient data with the reason, and no divergence figure is reported\n\nScenario: Small samples suppress the threshold check\n  Given fewer comparable orders than the configured minimum\n  When the job evaluates thresholds\n  Then the sample size is reported and the threshold check is skipped with that stated, rather than firing on noise\n\nScenario: Recording gaps exclude a symbol honestly\n  Given a symbol whose recorded coverage has gaps in the window\n  When the job selects symbols\n  Then that symbol is excluded with the gap named, because an unfaithful replay would produce a meaningless comparison\n\nScenario: Results are queryable by date\n  Given several nights of results\n  When the fidelity endpoint is queried for a date range\n  Then each night's metrics are returned with their thresholds and outcomes\n```",
   tech="- The job reuses the replay engine (E26) and the same event bus as production, so the comparison exercises the real matcher rather than a test double - this is the whole point of the architecture's shared-bus design (`docs/plan/24-internal-schemas.md` section 13).\n- Slippage difference is computed per order as (simulated average fill price - real average fill price) expressed in ticks, signed so a systematically optimistic simulator is visible as a consistent direction rather than cancelling out in the mean; report both mean (bias) and p95 (tail).\n- Fill-rate difference applies only to resting limit orders, where queue modelling is the uncertain part; market orders are compared on slippage only.\n- The job is idempotent per (date, symbol) so a re-run overwrites rather than duplicating.\n- Runs off-peak and is cancellable; it must never contend with live ingestion for CPU.",
   test="- Unit: metric computations against hand-computed fixtures, incl. the sign convention for bias.\n- Unit: threshold evaluation at the boundary (exactly 1 tick, exactly 10 pp) and under the minimum sample size.\n- Unit: insufficient-data and coverage-gap paths produce explicit reasons.\n- Unit: idempotent re-run.\n- Integration: a seeded recorded day plus fixture demo fills produces a full report document; a deliberately mis-tuned fill model produces a threshold breach and a defect record.\n- Contract: the fidelity endpoint against OpenAPI.\n- Coverage: >=85%.",
   sec="- The job reads recorded market data and the account's own fills; no credential use beyond the existing fee-rate lookups.\n- Threat: a silently failing job giving false assurance that the simulator is honest. Control: the job's own liveness is monitored and a missed night alerts - absence of a report is treated as a failure, not as a pass.\n- Data classification: trading data, internal.",
   a11y="N/A - backend job. Its output is rendered on SCR-137 following that screen's accessibility rules.",
   perf="- Must complete within the off-peak window for a full day of the recorded symbol set; target under 30 minutes for 10 symbols, leaning on the matcher's 20x-faster-than-real-time requirement from E38-S03.\n- Must not exceed the per-symbol backend memory budget #8 while replaying.",
   obs="- Metrics `cv_paper_divergence_slippage_ticks{symbol,stat}`, `cv_paper_divergence_fill_rate_pp{symbol}`, `cv_paper_divergence_job_duration_seconds`, `cv_paper_divergence_job_last_success_timestamp`.\n- Alert on threshold breach and on a missed run (stale last-success timestamp).\n- Structured log of the `FillModelConfig` used, so a breach is attributable to a configuration as well as to code.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-S03` (the matcher being measured), `E38-S01` (real demo fills to compare against), `E26` (replay engine and recorded data).",
   branch="`feat/e38-paper-divergence`; PR size: ~300 LOC plus fixtures.",
   refs="- `docs/plan/24-internal-schemas.md` section 12.5 (normative), section 13 replay bus\n- `docs/plan/20-architecture.md` section 3.7\n- `docs/plan/22-api-openapi.yaml` `GET /market/data-coverage`\n- `docs/plan/32-risk-register.md` R12"))
