# -*- coding: utf-8 -*-
from _e38_gen import t, body, MS, PH, AREA, DOD_COMMON, DOD_UI

ST = dict(kind="Story", phase=PH, milestone=MS, perspective="Development", parent="E38")

t(**ST, key="E38-S03", component="backtesting", title="Simulate fills locally with the paper matcher's queue, latency and fee models",
  labels=["type/feature", AREA, "priority/p1", "perf"], sprint="Sprint 18",
  priority="P1 High", risk="R12 Backtest bias", estimate=5, blocked_by=["E38-S01", "E26", "E29"],
  body=body(
   ctx="US-PAPER-004 (Should) asks for an offline simulator so the owner can practise and develop with no exchange dependency, and so rule simulation and replay have somewhere to execute. Its NFR is the design constraint: 'simulator uses the same OMS state machine as real trading so behaviour is comparable'.\n\n`docs/plan/24-internal-schemas.md` section 12 specifies the matcher in full and is normative for this story: the `FillModelConfig`, the book-walk for market orders, the queue-position model for resting limits (including the pro-rata cancel assumption described there as 'the single most important honesty knob in the whole simulator'), latency, fees from `GET /v5/account/fee-rate`, funding as an `Execution` with `exec_type=\"funding\"`, and margin/liquidation from real tiered risk-limit data. `docs/plan/20-architecture.md` section 3.7 names the components: `FillModel`, `QueueEstimator`, `FeeModel`, `PaperLedger`.\n\nThe point of all this detail is honesty: a simulator that ignores queue position, latency and funding lies, and a lying simulator is worse than none because it manufactures confidence (risk R12).",
   scope="- Implement module **M16 Paper Matcher** in `packages/backend/cv/paper/`: `FillModel`, `QueueEstimator`, `FeeModel`, `PaperLedger`, exposing the **same interface as the exchange adapter** (`docs/plan/24-internal-schemas.md` section 14) so the OMS routes to it without knowing it is a simulation.\n- `FillModelConfig` exactly as specified in section 12.1 (all fields, same defaults: `mode=book_walk`, `use_queue_position=True`, `prob_fill_on_touch=0.35`, `latency_submit_ms=60`, `latency_cancel_ms=60`, `latency_market_data_ms=30`, `max_book_levels=200`, `reject_if_book_exhausted=True`, `apply_funding=True`).\n- Market orders: walk the opposite side of the live/replayed L2 book from best, one `Execution` per level consumed, volume-weighted average price; `INSUFFICIENT_LIQUIDITY` rejection when the book is exhausted and `reject_if_book_exhausted` is set, else fill at last level plus `slippage_floor_ticks`.\n- Limit orders: crossing fills as taker capped at the limit price with the remainder resting; `post_only` that would cross is **rejected**, as the exchange does.\n- Resting limits with queue position: snapshot same-side displayed size as `queue_ahead`; decrement by same-side prints at the level; fill only past a cleared queue; clear the estimate when price moves away; re-cap on return; and on a level shrinking without a print, apply the pro-rata assumption `queue_ahead *= new_level_size / old_level_size`.\n- Latency: orders become live at `submit_ts + latency_submit_ms`, cancels take effect at `cancel_ts + latency_cancel_ms` (so a cancel can lose the race), decision market data delayed by `latency_market_data_ms`.\n- Fees from `GET /v5/account/fee-rate` cached 24 h, `is_maker` true only for a resting limit filled by an incoming aggressor, negative maker rates supported, `fee_estimated=True` marking when defaults (maker 2 bps / taker 5.5 bps) are used.\n- Funding at each `next_funding_time` using the real rate and `instrument.funding_interval_min` (never assumed 8 h), recorded as an `Execution` with `exec_type=\"funding\"`, `qty=0`.\n- Margin, liquidation and the `adl_risk_proxy` per section 12.4, using fetched `GET /v5/market/risk-limit` tiers, never hardcoded.\n- `PaperLedger` persists positions, wallet and realised/unrealised PnL in Postgres with the **identical schema to live accounts** (`is_paper=true` on the rows) so every downstream view is account-type agnostic.\n- Hard interlock: the matcher has **no network transport**; a structural test asserts `cv/paper/` imports no HTTP or WS client.",
   oos="- The SCR-099 results UI (E38-S05) and the simulated labelling system it renders.\n- The nightly divergence job (E38-S05's dependency is only the display; the job itself is E38-T03).\n- Bybit demo routing (E38-S01) - demo is a real engine, this is the local one.\n- Backtesting over historical bars as a product feature (E26 replay owns the data source; this is the fill engine it drives).",
   ac="```gherkin\nScenario: Limit fills when the book and prints would have filled it\n  Given simulator mode against live market data\n  When a limit order is placed and the level trades through after the estimated queue ahead is consumed\n  Then it fills, applying the configured latency and slippage model, with one Execution per consuming print\n\nScenario: Market order walks the book rather than filling at one price\n  Given a market order larger than the best level\n  When it is matched\n  Then it produces one Execution per level consumed and an average price equal to the volume-weighted result\n\nScenario: Book exhaustion rejects rather than inventing liquidity\n  Given reject_if_book_exhausted is true and the order exceeds total displayed depth\n  When it is matched\n  Then the remainder is rejected with INSUFFICIENT_LIQUIDITY\n\nScenario: post_only that would cross is rejected\n  Given a post_only limit priced through the opposite best\n  When it is submitted\n  Then it is rejected exactly as the exchange would reject it\n\nScenario: A cancel can lose the race\n  Given a resting order about to be filled and a cancel submitted within the cancel latency window\n  When the fill occurs before cancel_ts plus latency_cancel_ms\n  Then the order fills and the cancel is rejected as too late\n\nScenario: Queue shrinkage is treated conservatively\n  Given a level that shrinks without any trade print\n  When the queue estimate is updated\n  Then queue_ahead is reduced only pro rata to the level size change, never to zero\n\nScenario: Funding is a real P&L component\n  Given an open simulated position held across a funding timestamp\n  When funding settles\n  Then an Execution with exec_type funding and qty zero is written with the signed payment using the real rate and the instrument's funding interval\n\nScenario: Model disclosure is machine-readable\n  Given a completed simulated session\n  When its results are requested\n  Then the applied FillModelConfig is returned alongside them so the panel can state queue position, latency, slippage and fee assumptions\n\nScenario: The simulator can never place an exchange order\n  Given simulator mode\n  When any order is submitted\n  Then no network call is made, and a structural test asserts the paper package imports no HTTP or WS client\n\nScenario: Simulated state is marked everywhere\n  Given simulated orders, executions and positions\n  When they are persisted and published\n  Then every row and every WS frame carries is_paper true\n```",
   tech="- The matcher consumes the **same event bus** the live path uses (`docs/plan/24-internal-schemas.md` section 13: replay re-emits recorded events onto the same bus with the same types), so it works identically over live and replayed data without a second code path.\n- Determinism is a requirement, not a nicety: given the same event sequence and config, the matcher must produce byte-identical executions, because rule simulation (`docs/plan/24-internal-schemas.md` section 11) and R3 exit criterion 6 depend on deterministic replay. Seed any randomness explicitly from the session id.\n- All monetary arithmetic uses `Decimal` with the instrument's tick/lot precision; fees quantized to 8 dp `ROUND_HALF_UP` as specified.\n- The matcher is per paper account, in-memory plus Postgres (`docs/plan/20-architecture.md` C11), and must be restart-safe: ledger state is recoverable from Postgres, resting orders are re-registered with their persisted `queue_ahead`.\n- `is_paper` is orthogonal to `environment` - a paper fill still belongs to a real environment (demo, or live when replaying live-recorded data). Do not collapse them (`docs/plan/23-ws-protocol.md` section 13.1 comment).",
   test="- Unit: queue estimator - a dedicated table-driven suite covering trade-through, partial consumption, price-away clearing, re-cap on return, and the pro-rata cancel case; this is the highest-value test set in the story.\n- Unit: book walk with exact expected VWAP over a fixture book; exhaustion; `slippage_floor_ticks` behaviour.\n- Unit: latency race (cancel wins / cancel loses) at the boundary millisecond.\n- Unit: fee computation incl. maker rebate, estimated-fee marking, and cache expiry.\n- Unit: funding sign convention for long and short, non-8h intervals.\n- Unit: liquidation tier maths against fixture risk-limit data.\n- Property test: total simulated fill quantity never exceeds available displayed liquidity within the configured level cap.\n- Determinism test: the same recorded window replayed twice yields identical execution streams (supports R3 exit criterion 6).\n- Integration: a full replay session through E26 producing simulated positions and a closed ledger, restart-recovered mid-session.\n- Perf: 1 hour of recorded BTCUSDT ticks matched faster than real time by at least 20x, to support replay speeds.\n- Coverage target: >=90% on `cv/paper/` (engine package, local policy above the 85% floor).",
   sec="- Threat: the simulator reaching the network and placing a real order. Control: the structural no-transport test plus routing that only reaches the matcher for `is_paper` accounts; this is the story's single most important control and is re-checked in E38-X02.\n- Threat (R12): simulated results being mistaken for achievable results. Control: mandatory model disclosure returned with every result set, rendered by E38-S05.\n- Fee-rate calls use the account's real credentials through the vault; no new credential path is introduced.\n- Data classification: financial simulation data, internal.",
   a11y="N/A - backend engine. The disclosure payload it emits is what makes E38-S05's accessible disclosure block possible.",
   perf="- Matching must sustain replay at up to 100x (budget #15) without becoming the bottleneck; profile the queue estimator, which runs per print per resting order.\n- Memory: the matcher holds at most `max_book_levels` (200) per symbol plus resting orders; assert it stays inside the per-symbol backend memory budget #8 (<=300 MB).",
   obs="- Metrics: `cv_paper_fills_total{mode}`, `cv_paper_rejections_total{reason}`, `cv_paper_match_latency_seconds`, `cv_paper_queue_estimate_resets_total`.\n- Every simulated execution logs its `queue_ahead` at fill time, which is what makes the divergence job (E38-T03) able to attribute differences.\n- Structured log of the `FillModelConfig` used at session start, so any result set can be reproduced.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-S01` (the OMS routing and adapter interface are proven end to end first), `E26` (replay engine supplies recorded book and trade events on the shared bus), `E29` (OMS state machine the matcher must reuse rather than reimplement).",
   branch="`feat/e38-paper-matcher`; PR size: exceeds 400 LOC - split into (1) fill model + queue estimator, (2) fee/funding/margin, (3) ledger + persistence, each independently reviewable.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-004\n- `docs/plan/24-internal-schemas.md` section 12 (normative), section 13 replay bus, section 14 adapter\n- `docs/plan/20-architecture.md` section 3.7, C11 Paper Matcher\n- `docs/plan/21-database-schema.md` `is_paper` columns on orders/positions/executions\n- `docs/plan/06-performance-and-load-standard.md` budgets #8, #15"))

t(**ST, key="E38-S04", component="web", title="Show demo/live chrome everywhere and switch environments from the shell",
  labels=["type/feature", AREA, "priority/p0", "a11y", "design-qa", "security"], sprint="Sprint 19",
  priority="P0 Critical", risk="R9 Advice boundary", estimate=3, blocked_by=["E38-D06", "E38-S02", "E38-T02"],
  body=body(
   ctx="SCR-075 is called 'the single most safety-critical visual element in the app' in `docs/plan/14-screens-catalogue.md`, and US-PAPER-002's second scenario requires that 'a persistent accent and a text badge mark every trading-capable surface, and the badge is never colour-only'. US-PAPER-003 requires every trading-capable view to reflect and enforce the current environment.\n\nThis story builds SCR-074 (the switcher) and SCR-075 (the permanent chrome) against the signed-off designs from E38-D06 and the backend from E38-S02/T02.",
   scope="- **CMP-074 EnvBanner**: persistent global band in the app shell (SCR-010), rendering `DEMO`/`LIVE` as text plus icon plus pattern, never colour alone; `role=\"status\"` region read early in document order; never scrolled away and never covered by a modal. The demo variant states 'Demo uses Bybit's demo matching engine - REST order entry only, no private WS order entry.'\n- **CMP-075 EnvBadgeLocal**: repeated in the header of every trading-capable panel - order ticket (CMP-107), group ticket, DOM ladder, positions grid, algo monitor and the chart-trading overlay - and repeated in every floating window. `role=\"img\"` with a static label so it does not re-announce on each panel re-render.\n- Every trading panel's accessible name includes the environment ('Order ticket - LIVE - Main') per SCR-075.\n- **SCR-074 switcher modal**: opened only by clicking the band (no hotkey may be bound - assert this in the hotkey registry), listing live accounts available, stating that working orders in the current environment stay there and are not migrated, requiring the typed confirmation phrase plus step-up, and rendering all catalogued states: switching (with the phase progress from E38-S02's `system` frames), switched (10 s full-width confirmation banner), failed (stays on the previous environment with the reason), not permitted, and blocked-by-in-flight-activity with the blocker list.\n- **CMP-139 EnvironmentAwareOrderGuard**: wrap the order ticket and DOM click-to-trade handlers so a mismatch renders the wrapped control disabled-with-reason rather than silently rerouting; this is defence in depth over E38-T02's server check.\n- Order confirmation copy restates the environment ('You are about to send a **LIVE** order') per SCR-075.\n- A single shared environment store subscription feeds every badge; the band does not remount on route change.",
   oos="- The backend switch endpoint (E38-S02) and isolation middleware (E38-T02).\n- Parity report, reset, eligibility and simulated-results surfaces (S05-S08).\n- The step-up modal (E09).",
   ac="```gherkin\nScenario: Environment is visible on every trading-capable surface\n  Given any trading panel including a floated or maximised one\n  When it is rendered\n  Then it shows the environment badge in its header and includes the environment in its accessible name\n\nScenario: Switching is deliberate\n  Given the session is in Demo\n  When the user attempts to reach Live\n  Then the only path is clicking the band, typing the confirmation phrase and passing step-up, and no hotkey binding can invoke it\n\nScenario: One-click trading is disarmed on switch\n  Given one-click trading is armed\n  When the environment switches\n  Then the UI reflects the disarmed state returned by the server and no one-click action is operable until re-armed\n\nScenario: The transition blocks order entry\n  Given a switch is in progress\n  When the user attempts to submit an order\n  Then every order-entry control is disabled with the transition stated, and the phase progress is shown and announced\n\nScenario: A failed switch leaves the previous environment intact\n  Given the server returns a failure mid-transition\n  When the modal handles it\n  Then the previous environment's chrome is restored unchanged and the failure reason is displayed\n\nScenario: Not-permitted state is explanatory but not disclosing\n  Given a manager without live access\n  When they open the switcher\n  Then the switch action is disabled with the reason that the owner has not enabled Live for their account, without naming who does have access\n\nScenario: Mismatched order is blocked client-side too\n  Given the workspace environment context is demo and a control targets a live account\n  When submission is attempted\n  Then CMP-139 disables the control with a reason and no request is sent\n\nScenario: Distinguishable without colour\n  Given the built application\n  When rendered in greyscale and in three colour-vision simulations\n  Then DEMO and LIVE remain unambiguous\n```",
   tech="- One Zustand (or the project's chosen store) slice holds `{environment, phase, allowedEnvironments, armed}`, hydrated from `GET /auth/session` and updated from the `system` WS topic; badges subscribe with selectors so an environment change does not re-render panel bodies.\n- The band lives in the shell layout above the router outlet so it never unmounts on navigation; modals render in a portal *below* the band in stacking order.\n- The hotkey assertion is a unit test over the hotkey registry (`GET /settings/hotkeys` vocabulary) asserting no action id maps to the environment switch.\n- All colours come from `color.env.demo` / `color.env.live` tokens; a lint rule forbids literal hex in these components.\n- Phase progress consumes the `system` frames from E38-S02 rather than a client-side timer, so the UI cannot claim completion the server has not reached.\n- Electron: the band must render identically in detached/floating windows, which are separate BrowserWindows - the store is synchronised across windows via the existing IPC bridge, not duplicated fetches.",
   test="- Unit: badge renders text for each environment; accessible name composition for each panel type.\n- Unit: hotkey registry assertion (no binding reaches the switch).\n- Interaction (Testing Library): typed-confirm gate - the switch button stays disabled until the exact phrase is typed; cancel restores focus to the band.\n- Interaction: CMP-139 mismatch disables with reason and emits no request.\n- Storybook + visual regression: Demo, Live, SwitchConfirmFlow, switching, switched, failed, not-permitted, blocked - in both themes and both densities.\n- axe-core: zero violations on the shell with the band and on the open modal.\n- E2E Playwright (web and Electron, feeds E38-Q02): full switch with step-up; badge presence on every trading panel; floating-window badge; band not covered by a modal.\n- Coverage target: >=80% frontend.",
   sec="- This is the user-facing half of SR-040a and the visible part of US-PAPER-003. A missing or wrong badge is a `priority/p0-critical` security-labelled defect.\n- CMP-139 is defence in depth only - the test suite must include a case proving that bypassing the client guard still results in a server 403 (cross-referenced with E38-T02), so nobody is tempted to treat the client as the boundary.\n- Not-permitted copy must not disclose other users' grants.\n- No credential or key material is rendered on any of these surfaces.",
   a11y="- WCAG 2.2 AA per the E38-D05 annotation layer: band is `role=\"status\"` and polite; the post-switch confirmation is `role=\"alert\"` announced once; the modal traps focus, focuses the typed-confirm field on open and returns focus to the band on close; visible focus throughout; error states announced and associated with their field.\n- The environment distinction is text plus icon plus pattern (1.4.1); contrast >=4.5:1 text and >=3:1 non-text (1.4.3/1.4.11).\n- Reduced-motion: the chrome transition degrades to an instant swap.\n- Manual NVDA pass required; recorded on the ticket.",
   perf="- The band is part of the shell and must not remount on route change; verify with the React profiler.\n- An environment change must not trigger a full re-render of trading panels - only the badge subtree; assert with a render-count test.\n- No regression to budget #10 (cold start <=3 s) or #9 (bundle size) - the band and badges are tiny and must stay in the initial bundle since they are safety chrome and may never be lazily loaded.",
   obs="- Client analytics: switcher opened, confirmation typed, switch confirmed, switch cancelled, switch failed (with phase).\n- Verify the server-side `session.environment_switched` audit row appears after a UI-driven switch (checked in E38-D07 and E38-Q02).",
   dod=DOD_UI,
   deps="- `blocked_by: E38-D06` (signed-off handoff, design-ahead rule), `E38-S02` (switch endpoint and `system` phase frames), `E38-T02` (server-side isolation this UI reflects).\n- Consumes the app shell (SCR-010) and the order ticket (E30), DOM ladder (E31) and positions grid (E29) surfaces it badges - coordinate with those epics on header slot availability.",
   branch="`feat/e38-env-chrome-ui`; PR size: split into (1) store + band, (2) per-panel badges + guard, (3) switcher modal.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-002, US-PAPER-003\n- `docs/plan/14-screens-catalogue.md` SCR-074, SCR-075, SCR-010, SCR-076\n- `docs/plan/15-component-catalogue.md` CMP-074, CMP-075, CMP-139, CMP-044\n- `docs/design/handoff/E38.md`\n- `docs/plan/05-accessibility-standard.md`"))

t(**ST, key="E38-S05", component="web", title="Present simulated results with model disclosure and simulated-everywhere labels",
  labels=["type/feature", AREA, "priority/p1", "a11y", "design-qa"], sprint="Sprint 19",
  priority="P1 High", risk="R12 Backtest bias", estimate=2, blocked_by=["E38-D06", "E38-S03", "E26", "E41"],
  body=body(
   ctx="US-PAPER-004's third scenario requires that simulator positions are 'visually marked as simulated everywhere', and US-PAPER-005 requires paper results to be 'stored separately and never aggregate into live statistics, with a clear label on every view' and journaled 'with the same fields plus an environment tag'.\n\nSCR-099's design sign-off checklist demands that every figure carries the 'simulated' framing, that fill-model assumptions are stated explicitly, and that comparison against real trades is opt-in and clearly separated. This story ships SCR-099 and the cross-cutting `is_paper` labelling designed in E38-D04.",
   scope="- Build **SCR-099 Replay paper-trading results** as a drawer at the end of a replay session: simulated fills, P&L, R distribution, per-trade list with entry/exit and R, the modelled slippage assumptions, export (CMP-099), and the 'these results are not a backtest guarantee' caveat. Components: CMP-049 Table, CMP-099 PrintExportBar, CMP-116 PnLBadge, CMP-167 JournalEquityCurveChart, CMP-168 JournalStatsSummaryCard.\n- The **fill-model disclosure block**, rendered from the `FillModelConfig` returned by E38-S03 - queue position on/off, submit/cancel/market-data latency, slippage mode, fee source (live rate vs estimated default), funding applied - with each value shown, not merely named.\n- Opt-in comparison against the same period's real trades, **off by default**, with the two series visually and textually separated and never summed into one total.\n- The **simulated labelling system** applied across surfaces that render `is_paper` rows: orders blotter, positions grid, journal list, journal trade detail and analytics headers - badge in the heading and in the accessible name, not only a chip.\n- Analytics exclusion: paper rows are excluded from live statistics by default with an explicit, labelled include-toggle; promoting a session to the journal writes entries flagged `simulated=true`.\n- A table alternative for every chart on SCR-099, reachable by keyboard.",
   oos="- The matcher itself (E38-S03) and the divergence job (E38-T03).\n- Journal analytics computation (E41) - this story contributes the simulated treatment and the exclusion rule that E41's queries honour.\n- Replay transport controls (E26).",
   ac="```gherkin\nScenario: Every figure carries simulated framing\n  Given a completed replay paper session\n  When the results drawer opens\n  Then the word Simulated appears in the region heading and in the accessible name of every results region\n\nScenario: Fill-model assumptions are stated with their values\n  Given the session used a specific FillModelConfig\n  When the disclosure block renders\n  Then queue position, submit latency, cancel latency, market-data latency, slippage mode, fee source and funding application are each shown with the value actually used\n\nScenario: Estimated fees are flagged\n  Given the matcher fell back to default fee rates\n  When results render\n  Then the fee figures are marked as estimated, with the reason available\n\nScenario: Comparison is opt-in and separated\n  Given the comparison against real trades\n  When the drawer first opens\n  Then comparison is off, and when enabled the simulated and real series remain separately labelled and are never aggregated into a single total\n\nScenario: Paper results never aggregate into live statistics\n  Given a journal containing both simulated and real trades\n  When live analytics are computed\n  Then simulated rows are excluded by default and the include-toggle is explicit and labelled\n\nScenario: Every chart has a keyboard-reachable table alternative\n  Given the equity curve and the R distribution\n  When navigating by keyboard only\n  Then a table alternative for each is reachable and readable by a screen reader\n\nScenario: Promotion to journal is tagged and audited\n  Given the user promotes the session to the journal\n  When the entries are written\n  Then each is flagged simulated true and the action is audited as journal.simulated_import\n```",
   tech="- Results are computed server-side at session end and fetched once (SCR-099 performance note); the drawer has a skeleton state sized to the final layout and no live subscriptions remain open.\n- The simulated badge is a design-system component contributed by E38-D04, not a page-local element, so every consuming surface picks it up by upgrading the package.\n- `is_paper` drives the badge; `environment` drives the env badge. The two must render distinctly - a unit test asserts a demo simulated row shows both and that neither substitutes for the other.\n- Analytics exclusion is implemented as a default query filter in the journal data layer (coordinated with E41), not as a per-component filter, so a new view cannot accidentally include paper rows.\n- Chart colour/series encodings must be distinguishable without colour; prefer direct labelling over a legend for the two-series comparison.\n- Export reuses E41's CSV/Parquet export path with the simulated flag included as a column.",
   test="- Unit: disclosure block renders every `FillModelConfig` field including the estimated-fee marking.\n- Unit: badge placement rules across blotter/positions/journal/analytics; simulated and environment badges coexist.\n- Unit: analytics default excludes `is_paper` rows; the include-toggle changes the query, not just the display.\n- Interaction: comparison toggle defaults off; enabling never merges totals.\n- axe-core: zero violations on the drawer, incl. the table alternatives.\n- Storybook: populated, empty (no simulated trades), loading, error, comparison-on, estimated-fees.\n- E2E (feeds E38-Q02): run a short replay session with the paper matcher, open the drawer, export, promote to journal and assert the journal rows are flagged and audited.\n- Coverage target: >=80% frontend.",
   sec="- Threat R12: simulated results leaking into live performance statistics and driving real position sizing. Controls: data-layer default exclusion, mandatory labelling, audited promotion.\n- Export must not create an unauthenticated shareable artefact; it downloads through the authenticated session only.\n- Data classification: trading performance data, internal.",
   a11y="- 'Simulated' in headings and accessible names (SCR-099 a11y note); results are a table plus a summary description list.\n- Table alternative for every chart, keyboard reachable, with a programmatic association to the chart it replaces.\n- Export controls have accessible names stating format and scope.\n- Badge is not colour-only; contrast verified per E38-D05's measurements.\n- Manual screen-reader pass required.",
   perf="- Single fetch at session end; no open subscriptions. The per-trade table virtualises above 200 rows.\n- Rendering the drawer must not disturb the chart frame budget (#1) if a chart is still mounted behind it - measure with the profiler during the replay-to-results transition.",
   obs="- Emit `replay.results_viewed`, `replay.results_exported` and `replay.results_promoted_to_journal`; the last is audited as `journal.simulated_import` (SCR-099 analytics/audit note).\n- Count include-toggle activations on analytics - frequent use suggests the default is wrong and is worth revisiting with the Owner.",
   dod=DOD_UI,
   deps="- `blocked_by: E38-D06` (handoff), `E38-S03` (matcher output and its config disclosure), `E26` (replay sessions produce the results), `E41` (journal/analytics data layer and chart components CMP-167/168 this composes).",
   branch="`feat/e38-simulated-results-ui`; PR size: split into (1) simulated badge + labelling rollout, (2) SCR-099 drawer.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-004, US-PAPER-005, US-RPL-006\n- `docs/plan/14-screens-catalogue.md` SCR-099\n- `docs/plan/24-internal-schemas.md` section 12.1 FillModelConfig\n- `docs/plan/15-component-catalogue.md` CMP-049, CMP-099, CMP-116, CMP-167, CMP-168\n- `docs/design/handoff/E38.md`"))
