# -*- coding: utf-8 -*-
from _e38_gen import t, body, MS, PH, AREA, DOD_COMMON, DOD_UI

BE = dict(kind="Task", component="api", phase=PH, milestone=MS, perspective="Development", parent="E38")
ST = dict(kind="Story", phase=PH, milestone=MS, perspective="Development", parent="E38")

t(**dict(kind="Spike", component="api", phase=PH, milestone=MS, perspective="Architecture", parent="E38"),
  key="E38-K01", title="Spike: enumerate real Bybit demo-vs-live behavioural differences",
  labels=["type/spike", AREA, "priority/p1", "security"], sprint="Sprint 17",
  priority="P1 High", risk="R6 Feed rot", estimate=2, blocked_by=["E27", "E29"],
  body=body(
   ctx="US-PAPER-008 requires a parity report 'generated from a maintained data file plus runtime observations, never hand-written prose only'. We cannot maintain a data file we have not populated, and the roadmap's R3 goal 5 is to 'prove demo/live parity gaps explicitly so R4 is a gating exercise rather than a re-architecture'.\n\nWe already know three differences from research (`docs/plan/04-security-program.md` SR-040a): demo has no WS order entry, demo has no public WS (mainnet public streams are used for market data), and demo batch orders are limited to `linear`/`option`. `docs/plan/21-database-schema.md` adds a fourth (7-day demo order retention). This spike establishes the rest empirically instead of guessing, and produces the seed content for the parity data file that E38-S08 renders.",
   scope="- Timebox: **4 working days**, one backend engineer, against a real `api-demo.bybit.com` account created for the purpose.\n- Systematically exercise, on demo and on a read-only live account, each v5 surface the product uses: order create/amend/cancel, cancel-all, batch endpoints, conditional/TP-SL orders with `tpslMode` Full/Partial, trailing stops, position mode and leverage changes, `GET /v5/account/fee-rate`, `GET /v5/market/risk-limit`, `GET /v5/order/history`, `GET /v5/position/closed-pnl`, wallet balance, and the private WS `order`/`execution`/`position`/`wallet` streams.\n- For each: record supported / unsupported / behaves-differently, the exact `retCode`/`retMsg` when unsupported, the observed latency, and any field that is absent or differently populated on demo.\n- Record rate-limit behaviour differences (does demo return `10006`/`10018` on the same thresholds?).\n- Record how long demo order history is actually retained.\n- Produce `docs/plan/27-adrs/ADR-0016-demo-live-parity.md` recording the decision on which differences are *encoded in the capability matrix* (hard, compile-time), which are *documented in the parity report* (soft, informational), and which are *runtime-detected only*.\n- Produce the first version of the parity data file (`packages/backend/cv/paper/parity_items.yaml`) with one entry per confirmed difference: id, area, description, source (doc URL or observed), severity, last_verified date.",
   oos="- Implementing the capability matrix (E38-T01) or the report UI (E38-S08).\n- Any live order placement - the live account used is read-only and unfunded.\n- Non-USDT-perp product lines (spot, options, inverse) - out of product scope.",
   ac="```gherkin\nScenario: Every used v5 surface is classified\n  Given the list of Bybit v5 endpoints and WS topics this product calls\n  When the spike completes\n  Then each has a recorded demo classification of supported, unsupported or behaves-differently, with evidence\n\nScenario: Unsupported operations have exact error signatures\n  Given an operation unsupported on demo\n  When it is attempted\n  Then the observed retCode and retMsg are recorded verbatim, so E38-S01 can map them to a plain-language refusal rather than a generic failure\n\nScenario: The decision is recorded as an ADR\n  When the spike completes\n  Then ADR-0016 exists stating which differences are hard capability-matrix entries and which are informational parity items, with rationale\n\nScenario: The parity data file is seeded\n  When the spike completes\n  Then parity_items.yaml contains at least the four already-known differences plus every newly discovered one, each with a last_verified date\n\nScenario: A discovery that invalidates a design escalates\n  Given a difference is found that breaks an existing E29/E32/E33 design assumption\n  Then a risk entry is added to docs/plan/32-risk-register.md and the owning epic is notified before the spike closes\n```",
   tech="- Use a scripted harness under `packages/backend/tests/manual/demo_probe.py` so the probe is repeatable later as the re-verification mechanism for US-PAPER-008's 90-day staleness rule - this is deliberately not throwaway.\n- The harness reads credentials only through the envelope-encrypted store (SR-004: never from env vars or config files).\n- Probe results are written as machine-readable YAML, not prose, so the parity file can be diffed on each re-run.\n- Classify each difference against `docs/plan/04-security-program.md` SR-040a: anything that could cause a *silent* wrong-transport or dual-dispatch is a hard capability-matrix entry, not a documentation note.",
   test="- Not production code beyond the reusable probe harness; the harness itself gets unit tests for its result-parsing and YAML emission.\n- The probe must be runnable in CI against recorded fixtures (`CV_FEED=synthetic`) to verify the harness without credentials - SR-140 forbids demo credentials in CI.",
   sec="- Threat: a probe script leaking credentials into logs or the repo. Controls: credentials from the encrypted store only (SR-004), output redaction per the standard redaction rules (SR-146), the probe's YAML output asserted to contain no key-shaped strings before commit.\n- Threat (W9, `docs/plan/04-security-program.md`): code assuming WS order entry exists on demo. This spike's output is the evidence base for making that unreachable by construction.\n- Data classification: the demo account holds no real funds; its keys are still secrets and are handled identically to live keys.",
   a11y="N/A - no UI.",
   perf="- Record observed demo REST latency per endpoint so budget #4 (order submit to ack p95 <300 ms on demo, a hard R3 gate in `docs/plan/06-performance-and-load-standard.md`) can be assessed against reality before the stories commit to it.",
   obs="- The probe emits a structured summary suitable for later scheduling as the nightly/quarterly re-verification job feeding the parity report's `last_verified` field.",
   dod="- [ ] All classification questions answered with recorded evidence (raw responses archived).\n- [ ] ADR-0016 written in `docs/plan/27-adrs/` per `docs/plan/02-definition-of-ready-done.md` section 5.2.\n- [ ] `parity_items.yaml` seeded and reviewed by the Architect.\n- [ ] Follow-up tickets filed for any difference that requires code beyond the planned E38 scope.\n- [ ] Findings presented at Sprint Review; `docs/plan/32-risk-register.md` updated if a new risk surfaced.\n- [ ] Probe harness merged with tests (it is explicitly not throwaway) or explicitly archived with reason.",
   deps="- `blocked_by: E27` (accounts and the key vault exist, so a demo key can be stored properly) and `E29` (the OMS and adapter interface exist to probe through).",
   branch="`spike/e38-demo-parity-probe`; PR size: harness plus YAML plus ADR, small.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-008, US-PAPER-001\n- `docs/plan/04-security-program.md` SR-040a, SR-004, SR-140, SR-146, threats W9/W10\n- `docs/plan/24-internal-schemas.md` section 14 exchange adapter interface\n- `docs/plan/30-release-roadmap.md` section 7.1 goal 5"))

t(**BE, key="E38-T01", title="Environment capability matrix and demo host routing in the exchange adapter",
  labels=["type/tech", AREA, "priority/p0", "security"], sprint="Sprint 18",
  priority="P0 Critical", risk="R6 Feed rot", estimate=2, blocked_by=["E38-K01", "E29", "E27"],
  body=body(
   ctx="`docs/plan/04-security-program.md` **SR-040a** is unambiguous: 'the environment capability matrix MUST be enforced in code, not documentation'. A single `ExchangeEnvironment` value selects an immutable capability record and every transport call asserts against it. Demo uses `api-demo.bybit.com` for orders only, has **no WS Trade** and **no public WS** (mainnet public streams supply market data), and limits batch orders to `linear`/`option`.\n\nThreats W9 and W10 in the security program describe exactly what happens without this: a silent fallback or dual dispatch leaving orders unplaced or duplicated, and demo/live endpoints mixed within one session. This task makes both unreachable by construction and is the foundation every other E38 ticket stands on.",
   scope="- Add an immutable `EnvironmentCapabilities` record in `packages/backend/cv/exchange/capabilities.py`, keyed by `Environment` (`live`|`demo`|`testnet`, matching `docs/plan/24-internal-schemas.md` section 1.2 and the Postgres `exchange_env` type), carrying: REST base URL, public WS URL (or `None`), private WS URL, `ws_trade_supported: bool`, `batch_order_categories: frozenset[str]`, `order_history_retention_days`, and the parity-item ids that justify each restriction.\n- Wire the adapter (`docs/plan/24-internal-schemas.md` section 14 exchange adapter interface) so **one client instance exists per environment**, with no shared base-URL mutation - mixing endpoints in one session must be impossible by construction, not by convention.\n- Every transport call asserts its capability before dispatch and raises `CapabilityUnsupported(operation, environment, parity_item_id)` when unsupported; there is no fallback path and no dual dispatch.\n- Order entry is REST-only in **both** environments for v1 (WS Trade is an explicit non-goal); the code path is structured so that if WS Trade is ever enabled it is gated on `env == live` by the capability record.\n- Public market-data subscriptions for a demo trading session resolve to the **mainnet** public streams, and this resolution is explicit and logged, not incidental.\n- A CI assertion that no Bybit host string appears anywhere except `capabilities.py` (extending the SR-119 CSP assertion).\n- Contract test `enum_parity_environment` continues to pass: `Environment` is identical across `docs/plan/22-api-openapi.yaml`, `docs/plan/24-internal-schemas.md` and the PG type, and `paper` is a member of none of them.",
   oos="- The request-time isolation middleware for API routes (E38-T02).\n- The local paper matcher (E38-S03).\n- Any UI.",
   ac="```gherkin\nScenario: Demo order entry routes to the demo host\n  Given a session whose environment is demo\n  When an order is submitted through the adapter\n  Then the request goes to api-demo.bybit.com and no mainnet order host is contacted\n\nScenario: WS trade on demo is unreachable\n  Given the demo capability record\n  When any code path attempts WS order entry\n  Then a CapabilityUnsupported error is raised before any network call, and a unit test asserts no demo code path can reach a WS trade transport\n\nScenario: Batch order category restriction is enforced\n  Given a demo session\n  When a batch order is submitted for a category outside linear and option\n  Then it is refused locally with the parity item id attached, without contacting the exchange\n\nScenario: Environments cannot be mixed in one session\n  Given a live adapter client and a demo adapter client\n  When their configurations are inspected at runtime\n  Then they are separate instances with immutable base URLs, and a test asserting that mutating one leaves the other unchanged passes\n\nScenario: Market data for a demo session uses mainnet public streams\n  Given a demo trading session\n  When public market-data subscriptions are established\n  Then they connect to the mainnet public stream host, and the resolution is recorded in a structured log line\n\nScenario: A new host cannot be introduced silently\n  Given a developer adds a Bybit hostname outside capabilities.py\n  When CI runs\n  Then the host-location assertion fails the build\n```",
   tech="- `EnvironmentCapabilities` is a frozen pydantic model constructed once at import; there is no setter and no environment variable that can override a URL at runtime (SR-004's spirit: transport identity is not configuration).\n- `CapabilityUnsupported` maps to the RFC 9457 problem type used for refusals so the UI can render the plain-language message required by US-PAPER-001's 'Demo-only limitation' scenario; the problem body carries `parity_item_id` so the UI can deep-link into the parity report (E38-S08).\n- Capability records reference `parity_items.yaml` ids produced by E38-K01, so the code and the user-facing report cannot drift apart - a capability with no matching parity item fails a unit test.\n- Testnet is included in the enum for completeness but is used for smoke tests only per the locked decisions; its record mirrors demo unless K01 found otherwise.",
   test="- Unit: one test per capability field per environment; a parametrised test asserting every adapter operation checks a capability before dispatch (introspection over the adapter's method registry, so a newly added un-guarded method fails).\n- Unit: `CapabilityUnsupported` carries a real parity item id that resolves in `parity_items.yaml`.\n- Contract: `enum_parity_environment` (`docs/plan/24-internal-schemas.md` section 19.8) green.\n- Integration: against recorded fixtures, a demo-configured adapter performs a full submit/amend/cancel cycle over REST and never opens a trade WS.\n- CI gate: the Bybit-host location assertion.\n- Coverage target: >=90% on `cv/exchange/capabilities.py` (this is safety-critical code, above the 85% floor).",
   sec="- Directly implements **SR-040a**; supports **SR-119** (no exchange contact from the renderer; one chokepoint in the backend).\n- Mitigates threats **W9** (tampering: assumed WS order entry on demo causing unplaced or duplicated orders) and **W10** (spoofing: mixed demo/live endpoints in one session).\n- Data classification: no secrets in this module - it holds hosts and capability booleans only; credentials remain in the vault (E27).\n- `security` label required; Security engineer review is mandatory before merge.",
   a11y="N/A - no UI. The user-facing message carried by `CapabilityUnsupported` is rendered accessibly by E38-S01.",
   perf="- Capability checks are dictionary lookups on frozen objects, resolved once per call; the added cost must be immeasurable against budget #4 (order submit to ack p95 <300 ms on demo). Assert with a microbenchmark that the guard adds <0.1 ms per call.",
   obs="- Structured log on adapter construction: environment, resolved REST host, resolved public WS host, `ws_trade_supported`.\n- Counter `cv_capability_refusals_total{operation,environment}` - a non-zero value on live is an alertable anomaly.\n- Every `CapabilityUnsupported` is logged at warning with the operation and parity item id, and feeds the runtime-detected candidate parity items in E38-S08.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-K01` (the empirically confirmed difference list), `E29` (adapter interface and OMS exist), `E27` (per-environment accounts and keys exist).\n- Consumed by every other E38 backend ticket and by E44's live-enablement gating.",
   branch="`feat/e38-capability-matrix`; PR size: ~250 LOC plus tests.",
   refs="- `docs/plan/04-security-program.md` SR-040a, SR-119, threats W9/W10\n- `docs/plan/24-internal-schemas.md` section 1.2 Environment, section 14 adapter interface\n- `docs/plan/21-database-schema.md` `exchange_env` type\n- `docs/plan/20-architecture.md` section 3.7, section 9"))

t(**BE, key="E38-T02", title="Server-side environment isolation middleware with 403 and high-severity audit",
  labels=["type/tech", AREA, "priority/p0", "security"], sprint="Sprint 18",
  priority="P0 Critical", risk="R9 Advice boundary", estimate=3, blocked_by=["E38-T01", "E29", "E09"],
  body=body(
   ctx="US-PAPER-003 is a Must: 'every trading-capable view gated by environment, so that the two can never mix', with the explicit NFR 'enforced in one middleware layer with tests covering every trading route'. Its third scenario is the hard one: **a crafted request targeting a live account from a demo session must be rejected with 403 and audited as a high-severity event**.\n\nUS-PAPER-002's NFR adds that 'environment is part of every trading request; a mismatch between client intent and server session is rejected'. The client-side guard CMP-139 is defence in depth only - this task is the real boundary. It is also the environment leg of the RBAC 4-tuple `(permission, account scope, symbol allowance, environment enabled)` from `docs/plan/04-security-program.md` section 7.",
   scope="- One FastAPI dependency/middleware in `packages/backend/cv/api/deps/environment.py` applied to **every** mutating trading route: `POST /orders`, `PATCH /orders/{orderId}`, `DELETE /orders/{orderId}`, `POST /orders/cancel-all`, `POST /trade-groups`, `POST /trade-groups/{id}/amend`, `POST /trade-groups/{id}/cancel`, `POST /trade-groups/preview`, `POST /positions/{id}/tpsl`, `POST /positions/{id}/close`, `POST /positions/{id}/reverse`, `POST /positions/{id}/leverage`, `POST /positions/close-all`, `POST /rules/{ruleId}/mode` (arming), `POST /alerts/{alertId}/enabled` where the alert has a trading action, and `POST /trading/kill-switch`.\n- The check: resolve the target account(s) from the request, read their `env` from `exchange_accounts` (`docs/plan/21-database-schema.md` section 3.2), compare against the session's active environment and the user's `allowed_environments`; any mismatch is a `403` RFC 9457 problem with a stable error code and **no state change**.\n- **Mixed-group prevention**: reject creation of, and submission to, any trade group whose member accounts do not all share one `env` - enforced both at `POST /trade-groups` and at submit, complementing the existing DB constraint `tg_paper_env` and the `trg_ea_env_parent` trigger.\n- Audit every rejection as a high-severity event with the attempted environment, the session environment, the target account and the route; emit on the `system` WS topic so the admin security centre sees it live.\n- A **route-coverage test** that enumerates the OpenAPI document, selects every route tagged `trading` (or otherwise account-mutating), and asserts each one carries the environment dependency - a newly added trading route without the guard fails CI.",
   oos="- The switch endpoint itself (E38-S02).\n- Per-user live eligibility grants (E38-S07) - this middleware consumes `allowed_environments`, it does not manage it.\n- Frontend guarding (CMP-139, E38-S04).",
   ac="```gherkin\nScenario: Crafted cross-environment request is refused and audited\n  Given a session whose active environment is demo\n  When a request is crafted targeting a live exchange account\n  Then the response is 403, no order is created, and an audit row of high severity is written naming both environments and the target account\n\nScenario: Every trading route is covered\n  Given the generated OpenAPI document\n  When the route-coverage test runs\n  Then every account-mutating route has the environment dependency attached, and adding a new trading route without it fails CI\n\nScenario: Mixed-environment trade group is impossible\n  Given a set of accounts containing one demo and one live account\n  When a trade group is created from them\n  Then creation is refused with 422, and a separate test asserts submission to an already-existing mixed group is also refused\n\nScenario: Environment mismatch between client intent and session\n  Given a request that explicitly declares environment live\n  And a session whose active environment is demo\n  When the request is processed\n  Then it is rejected before reaching the OMS, with the mismatch named in the problem detail\n\nScenario: A user without the environment grant cannot use it\n  Given a manager whose allowed_environments contains only demo\n  When any live-targeting request is made, even with a valid live account id\n  Then it is refused with 403 and audited, regardless of the session's claimed environment\n\nScenario: Rejections do not leak other users' grants\n  Given a refusal caused by a missing live grant\n  When the problem detail is inspected\n  Then it states only that the caller lacks live access, never who does have it\n```",
   tech="- The dependency runs **after** authentication and permission resolution but **before** any handler body, so no partial work is possible; it is implemented as a FastAPI dependency returning a resolved `EnvironmentContext` that handlers must accept, making omission a type error rather than a silent gap.\n- Account resolution differs per route (body field, path param, trade-group membership); implement per-route extractors registered in one table, so the extractor list is reviewable in one place.\n- Error codes reuse the existing registry (`docs/plan/22-api-openapi.yaml` error registry) - add `environment_mismatch` and `environment_not_permitted` there rather than inventing ad hoc strings; the registry is single-source and has its own contract test.\n- Audit rows go through the existing append-only hash-chained audit writer (E42/`docs/plan/21-database-schema.md`), with event name `trading.environment_mismatch_rejected` at high severity.\n- The WS broadcast piggybacks on the `system` topic already used for environment switch notifications.",
   test="- Unit: matrix over (session env, target account env, allowed_environments) covering all combinations incl. the testnet value; assert 403 + no side effect + audit row for every disallowed cell.\n- Unit: mixed-group rejection at create and at submit.\n- Contract: OpenAPI route-coverage test described above; error-registry test for the two new codes.\n- Integration: against a seeded DB with one demo and one live account, drive each listed route with a crafted cross-environment payload and assert 403 with zero rows written to `orders`/`positions`.\n- E2E (feeds E38-Q02): the crafted-request scenario end to end, asserting the admin security centre shows the event.\n- Chaos-adjacent: assert the guard still refuses when the audit writer is unavailable - it must fail closed (refuse) rather than fail open.\n- Coverage target: >=90% on the middleware module.",
   sec="- Implements the environment leg of the RBAC 4-tuple (`docs/plan/04-security-program.md` section 7, `docs/plan/24-internal-schemas.md` section 15.2) and US-PAPER-003's server-enforcement scenario.\n- Threats: elevation of privilege (demo user reaching live), tampering (crafted account id), repudiation (an attempt with no audit trail). Controls: single choke point, fail-closed audit, high-severity event, route-coverage CI gate.\n- Data classification: request metadata and account ids; no secrets. Problem details must not disclose other users' grants (information disclosure).\n- `security` label mandatory; per `docs/plan/02-definition-of-ready-done.md` section 8 this ticket cannot reach Done without a Security engineer review comment and a manual privilege-escalation abuse check.",
   a11y="N/A - no UI. The 403 problem details are rendered by the frontend with the accessible disabled-with-reason pattern (E38-S04).",
   perf="- The guard adds one already-cached account lookup per request; assert p95 added latency <5 ms so budget #13 (write endpoints <300 ms p95 backend-internal) is unaffected. Account `env` is read from the request-scoped account cache, never a fresh query per leg of a fan-out.",
   obs="- Counter `cv_environment_rejections_total{route,session_env,target_env}`; any increment is alert-worthy on a healthy system.\n- Audit event `trading.environment_mismatch_rejected` (high severity), visible in SCR-137.\n- Trace span attribute `cv.environment` on every trading request, so a mis-routed request is diagnosable after the fact.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-T01` (capability matrix and per-environment clients), `E29` (trading routes and OMS exist), `E09` (sessions, RBAC and the permission resolution this layers onto).",
   branch="`feat/e38-env-isolation`; PR size: ~300 LOC plus a large test matrix - split tests into a second PR if the diff exceeds 400 LOC.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-003, US-PAPER-002 NFR\n- `docs/plan/04-security-program.md` section 7 RBAC 4-tuple\n- `docs/plan/21-database-schema.md` `exchange_accounts.env`, `tg_paper_env`, `trg_ea_env_parent`\n- `docs/plan/22-api-openapi.yaml` trading routes and error registry\n- `docs/plan/23-ws-protocol.md` `system` topic"))

t(**ST, key="E38-S01", component="api", title="Trade Bybit demo through the same code paths as live",
  labels=["type/feature", AREA, "priority/p0", "security"], sprint="Sprint 18",
  priority="P0 Critical", risk="R6 Feed rot", estimate=2, blocked_by=["E38-T01", "E29", "E27"],
  body=body(
   ctx="US-PAPER-001 (Must) is the foundation of the whole R3 train: every order in R3 executes against Bybit demo. Its NFR is the demanding part - 'identical code paths as live except host and key selection; contract tests run against both environments'. If demo needs its own branch in the OMS, R4's live enablement becomes a re-architecture instead of a gate flip (roadmap section 7.1 goal 5).\n\nE38-T01 gave us the capability record and host routing. This story proves the loop end to end: a demo order behaves, looks and is recorded exactly as a live one would, the demo private WS drives the UI identically, and an operation demo cannot do is refused in plain language rather than failing obscurely.",
   scope="- Wire the demo environment through the existing OMS order path (`docs/plan/24-internal-schemas.md` section 8 state machine): submit via REST to `api-demo.bybit.com` with `orderLinkId` idempotency, accept the REST response as *acceptance only*, and take order state from the demo **private WS** `order`/`execution`/`position`/`wallet` streams, exactly as live does.\n- Demo private WS client lifecycle: connect, authenticate, subscribe, heartbeat, reconnect with resubscribe, and the reconciliation loop against `GET /v5/order/realtime` and `/v5/position/list` on reconnect and on a timer - reusing E29's implementation, not a copy.\n- Map `CapabilityUnsupported` (E38-T01) and demo-specific exchange errors to a plain-language refusal carrying the operation, the reason and the parity item id, surfaced through the standard RFC 9457 problem body.\n- Ensure every persisted row carries the right environment: `orders.environment`, `positions`, `order_events.source`, and `is_paper=false` for demo (demo is a real matching engine - `is_paper` is orthogonal per `docs/plan/24-internal-schemas.md` section 1.2).\n- Run the existing OMS contract-test suite **twice**, once per environment, with only host and key selection differing; a divergence in the test outcome is a defect.\n- Ensure the 7-day demo order retention does not lose history: local `orders`/`executions`/journal mirroring already outlives the exchange's window (`docs/plan/21-database-schema.md` risk row 8) - add a regression test proving local history survives beyond the exchange's retention.",
   oos="- The local paper matcher (E38-S03) - demo is a real exchange engine, not a simulation.\n- The environment switch UX (E38-S02, E38-S04).\n- Live order entry, which remains gated off until R4/E44.",
   ac="```gherkin\nScenario: Demo order behaves as a live order\n  Given the session is in Demo with a demo-bound account\n  When an order is submitted\n  Then it is sent to the api-demo host and appears in positions exactly as a live order would, with the same fields populated\n\nScenario: Demo private stream drives the UI\n  Given a demo account with an open order\n  When the order fills at the exchange\n  Then order, execution, position and wallet updates arrive over the demo private WS and drive state identically to live, with the WS stream and not the REST ack as the source of truth\n\nScenario: Demo-only limitation is refused plainly\n  Given an operation unsupported in demo\n  When it is attempted\n  Then it is refused with the limitation stated in plain language and a parity item id, never a generic or obscure failure\n\nScenario: Identical code paths, proven\n  Given the OMS contract-test suite\n  When it is executed against demo and against live configuration\n  Then the only configuration difference is host and key selection, and both runs produce identical assertions\n\nScenario: Local history outlives exchange retention\n  Given demo orders older than the exchange's retention window\n  When the local order history is queried\n  Then the records are still present and complete, sourced from the local mirror\n\nScenario: Reconnect reconciles rather than duplicates\n  Given the demo private WS drops mid-order\n  When it reconnects\n  Then reconciliation against order/realtime restores exact state with no duplicated order and no lost fill\n```",
   tech="- No `if environment == demo` branches in the OMS. The only environment-aware code is the adapter's capability record (E38-T01) and key selection (E27's vault). A lint/architecture test asserts the string `demo` does not appear in `cv/oms/`.\n- Idempotency via `orderLinkId` is already the OMS contract; demo reuses it unchanged, which matters because demo's shorter retention makes a duplicate submission after reconnect more likely to look novel.\n- Plain-language refusals are composed from the parity item's `description` field, so the refusal text and the parity report cannot diverge.\n- `is_paper` stays `false` for demo orders; this is a frequent misunderstanding and is worth a comment plus a test, because setting it true would wrongly exclude demo results from analytics.",
   test="- Unit: error-mapping table from capability/exchange errors to plain-language refusals, including an unknown-error fallback that is still actionable.\n- Contract: the full OMS contract suite parameterised over both environments (the NFR's explicit demand).\n- Integration: recorded demo fixtures covering submit, partial fill, amend, cancel, rejection, and a reconnect mid-order; asserted against the state machine in `docs/plan/24-internal-schemas.md` section 8.\n- Integration: retention regression - synthesise an exchange history response missing old orders, assert the local mirror still serves them.\n- E2E (feeds E38-Q02): place a demo order from the ticket and observe it reach the positions grid.\n- Coverage target: >=85% backend; the error-mapping module >=90%.",
   sec="- Demo keys are secrets and are handled identically to live keys: envelope-encrypted, never returned by any API, never in logs (SR-003, SR-004, `docs/plan/04-security-program.md`).\n- Threat W9 (assumed WS order entry on demo) is structurally prevented by E38-T01; this story adds the behavioural test proving no demo order is ever dual-dispatched.\n- Repudiation: every demo order is audited exactly as a live order would be - demo is not an audit-free zone.\n- Data classification: financial transaction data (simulated funds, real structure).",
   a11y="- The plain-language refusal must be renderable as an accessible inline error associated with the control that triggered it; the frontend contract is specified in E38-D06's copy deck. No colour-only error indication.",
   perf="- Budget #4: order submit to ack p95 <300 ms on demo is a **hard R3 exit gate** (`docs/plan/06-performance-and-load-standard.md`). Measure and record on this story; if demo's own latency (from the E38-K01 probe) makes the budget unreachable, escalate rather than silently miss it.\n- The demo private WS must sustain the same fan-out budget #6 (<=20 ms p95 backend-internal add-on).",
   obs="- Metric `cv_orders_submitted_total{environment}` and `cv_order_ack_latency_seconds{environment}` so demo and live are comparable on one dashboard.\n- Log every capability refusal with operation and parity item id (feeds E38-S08's candidate items).\n- Alert if the demo private WS is disconnected for more than 30 s while orders are open.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-T01` (routing and capability record), `E29` (OMS, state machine, reconciliation loop), `E27` (demo account and its encrypted keys).",
   branch="`feat/e38-demo-integration`; PR size: ~300 LOC plus fixtures; split fixtures into their own PR if needed.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-001\n- `docs/plan/24-internal-schemas.md` section 8 OMS state machine, section 12 (demo vs local matcher table), section 14 adapter\n- `docs/plan/23-ws-protocol.md` private topics, `is_paper`\n- `docs/plan/21-database-schema.md` `orders`, `order_events`, risk row 8\n- `docs/plan/06-performance-and-load-standard.md` budgets #4, #6"))

t(**ST, key="E38-S02", component="api", title="Switch session environment safely with step-up and full resubscription",
  labels=["type/feature", AREA, "priority/p0", "security"], sprint="Sprint 18",
  priority="P0 Critical", risk="R9 Advice boundary", estimate=2, blocked_by=["E38-T02", "E09"],
  body=body(
   ctx="US-PAPER-002 (Must) requires switching to be 'deliberate and unmistakable'. `POST /session/environment` in `docs/plan/22-api-openapi.yaml` already specifies the contract: switching *to* `live` requires an elevated session (`/auth/step-up`) and the `live_trading` feature flag, else `403 step_up_required` or `403 live_trading_disabled`; the switch is audited and broadcast on the `system` WS topic so every pane re-badges consistently.\n\nSCR-074 adds the operational requirement that makes this non-trivial: on success the client tears down and re-establishes **every** private subscription, order entry is blocked for the whole transition, and 'a half-switched state is never reachable'.",
   scope="- Implement `POST /session/environment` per the OpenAPI contract: validate the target environment is in the caller's `allowed_environments`; for `live`, require an elevated session within the last 15 minutes and the `live_trading` flag on; otherwise return the specified 403 problem.\n- Refuse the switch while the session has **in-flight state that would be orphaned**: a running emulated algo (E33), an in-flight trade group (E34), or a pending order submission - returning a refusal that names the specific blocker (the SCR-074 design sign-off checklist requires this state to exist).\n- Orchestrate the transition server-side as an ordered, non-interleavable sequence: block order entry for the session, close private subscriptions for the old environment, re-derive the session's account scope and permissions for the new environment, open private subscriptions for the new environment, unblock. Any failure rolls back to the previous environment intact - never a partial state.\n- Broadcast the resulting environment on the `system` WS topic so every open pane and every other tab re-badges; include the transition phases so the UI can show the progress states SCR-074 specifies.\n- Audit `session.environment_switched` at high severity with from, to, user, session, and outcome; also audit refusals.\n- On switching to live, disarm one-click trading for the session (US-PAPER-002: 'one-click trading is disarmed on switch'), independently of the arm timeout in `POST /settings/arm`.\n- Working orders in the previous environment are **not** migrated and remain untouched; the response includes their count so the UI can state it.",
   oos="- The switch UI (E38-S04).\n- The step-up/2FA mechanism itself (E09).\n- The `live_trading` flag's administration (E42) and the R4 live-enablement gate (E44) - this story only reads the flag.\n- Per-user eligibility grants (E38-S07).",
   ac="```gherkin\nScenario: Switching to live requires step-up and the flag\n  Given a session that has not been elevated in the last 15 minutes\n  When a switch to live is requested\n  Then the response is 403 step_up_required, the environment is unchanged, and the refusal is audited\n\nScenario: Live trading disabled blocks the switch\n  Given the live_trading feature flag is off\n  And the session is elevated\n  When a switch to live is requested\n  Then the response is 403 live_trading_disabled and the environment is unchanged\n\nScenario: Successful switch resubscribes everything\n  Given a demo session with open private subscriptions\n  When a valid switch to live is performed\n  Then private subscriptions for demo are closed before any live subscription opens, the new environment is broadcast on the system topic, and order entry is blocked for the whole transition\n\nScenario: A half-switched state is never reachable\n  Given the resubscription step fails midway\n  When the transition aborts\n  Then the session is left fully on the previous environment with its subscriptions restored, and the failure reason is returned and audited\n\nScenario: Switching is blocked by in-flight activity\n  Given a running emulated algo or an in-flight trade group\n  When a switch is requested\n  Then it is refused with the specific blocker named, and no subscription is disturbed\n\nScenario: One-click trading is disarmed on switch to live\n  Given one-click trading is armed in demo\n  When the session switches to live\n  Then the armed state is cleared and a new explicit arm is required\n\nScenario: No hotkey path exists\n  Given the hotkey configuration surface\n  When all bindable actions are enumerated\n  Then no binding can invoke the environment switch\n```",
   tech="- The transition is guarded by a per-session lock; concurrent switch requests return `409` rather than interleaving.\n- Phases are emitted as `system` topic frames (`closing_subscriptions`, `reauthenticating`, `resubscribing`, `switched`) matching the SCR-074 progress states, so the UI is not guessing.\n- Rollback is structured as a compensating step per completed phase, executed in reverse order; a test injects failure at each phase boundary.\n- Account scope re-derivation reuses E09's session resolution rather than reimplementing it; the new scope must exclude every account whose `env` differs from the new environment.\n- The 'blocked by in-flight activity' check queries the algo and trade-group registries; the blocker list is returned as structured data, not a prose string, so the UI can render each blocker with a link.",
   test="- Unit: authorisation matrix over (target env, elevated?, flag state, allowed_environments) with the exact expected problem code for every cell.\n- Unit: rollback correctness with failure injected at each phase.\n- Unit: blocker detection for running algo, in-flight group and pending submission.\n- Contract: response and error shapes against `docs/plan/22-api-openapi.yaml`; `system` frame shape against `docs/plan/23-ws-protocol.md`.\n- Integration: full switch against a seeded two-environment account set, asserting subscription teardown/setup ordering from the WS server's connection log.\n- Integration: concurrent switch requests yield exactly one switch and one 409.\n- E2E (feeds E38-Q02): switch from demo to live with step-up on staging, asserting every open pane re-badges.\n- Coverage target: >=90% (safety-critical path).",
   sec="- This endpoint is the single gateway to live. Threats: elevation of privilege (switching without step-up), tampering (racing two switches into a mixed state), repudiation (an unaudited switch), denial of service (switch-flapping to disrupt subscriptions).\n- Controls: step-up requirement (SR-043-adjacent arming semantics), feature-flag gate, per-session lock, high-severity audit on success **and** refusal, rate-limit on the endpoint.\n- The refusal message for a missing grant must not reveal other users' grants (information disclosure).\n- `security` label mandatory; abuse-case checks are covered by E38-X02.",
   a11y="- The phase broadcasts exist so the UI can announce progress assertively (SCR-074 a11y note: the environment change is announced assertively and the chrome change is accompanied by a text badge change). The API must therefore emit phases promptly, not only a final result.",
   perf="- The whole transition should typically complete in <=2 s (SCR-074 performance note). Measure and record p95; the transition blocks order entry, so a slow switch is a trading outage.\n- Subscription teardown/setup must not thrash the WS fan-out budget; batch the resubscribe rather than issuing one frame per topic.",
   obs="- Audit `session.environment_switched` (high severity) plus `session.environment_switch_refused` with reason.\n- Metric `cv_environment_switch_duration_seconds` and `cv_environment_switch_failures_total{phase}`.\n- A failed rollback is a P0 alert - it implies a possibly half-switched session.",
   dod=DOD_COMMON,
   deps="- `blocked_by: E38-T02` (isolation middleware and the environment context it establishes), `E09` (step-up, sessions, RBAC).\n- Reads the `live_trading` flag owned by E42; the R4 gate that turns it on is E44.",
   branch="`feat/e38-session-environment`; PR size: ~300 LOC plus tests.",
   refs="- `docs/plan/11-user-stories.md` US-PAPER-002\n- `docs/plan/22-api-openapi.yaml` `POST /session/environment`, `POST /auth/step-up`, `POST /settings/arm`\n- `docs/plan/14-screens-catalogue.md` SCR-074 (states, performance, audit)\n- `docs/plan/23-ws-protocol.md` `system` topic\n- `docs/plan/04-security-program.md` SR-043"))
