# -*- coding: utf-8 -*-
"""E48 part 2 — design tickets (D01-D03)."""
from _e48_gen import t, T  # noqa

D01 = """## Context
E48 produces six distinct document sets (persona user guide, ops runbooks, DR playbook, API/WS reference, architecture/ADR index, engineer onboarding guide) plus changes to four in-app help surfaces. Without a deliberate information architecture these become a pile of markdown files that nobody can navigate under stress — and "under stress" is exactly the condition in which the runbooks are read.

`docs/plan/17-ux-diagrams.md` establishes the information-architecture conventions for the product; `docs/plan/16-design-system-brief.md` establishes tokens, type scale, density and motion. This ticket applies both to documentation as a first-class surface, and it must be Done two sprints before E48-S01/S02/T05 consume it (design-ahead rule, `docs/plan/00-planning-brief.md` and `docs/plan/02-definition-of-ready-done.md` §3.1). E48 engineering runs S25–S26, so this lands in **Sprint 23**.

The three reading modes this IA must serve are genuinely different and must not be collapsed into one template:
- **Learn** (user guide) — linear, persona-scoped, screenshot-heavy, read once calmly.
- **Do** (runbooks, DR playbook) — numbered, imperative, no prose, read at 03:00 with money at risk; each step states its expected observation so the reader can tell whether it worked.
- **Look up** (API/WS reference, architecture, ADR index) — searchable, deep-linkable, generated where possible.

## Scope / Deliverables
- **Light UX research** (half-day): the Owner (P1/P4) and one Account Manager (P2) are asked to find five specific answers using the current `docs/plan/` tree; time-to-answer and dead ends are recorded. 5–8 findings that justify the IA below.
- **Documentation IA map** (`docs/plan/17-ux-diagrams.md` addendum, mermaid): the `docs/` tree at GA — `docs/guide/` (persona guide), `docs/runbooks/`, `docs/runbooks/dr/`, `docs/reference/api/`, `docs/reference/ws/`, `docs/onboarding/`, `docs/plan/` (unchanged, planning history) — with the entry point for each persona and the rule for which tree a new document belongs in.
- **Three page templates**, specified to the token level against `docs/plan/16-design-system-brief.md`:
  - *Learn* template: front-matter block (title, persona(s), applies-to version, author, **non-author reviewer name + date** as required by `docs/plan/30-release-roadmap.md` §9.4), on-this-page nav, screenshot convention (theme, density, redaction), "what you cannot do and why" callout tied to the permission matrix in `docs/plan/10-personas.md` §7.
  - *Do* template: trigger ("you are here because…"), pre-conditions, numbered steps with an **Expected observation** column, abort/rollback step, escalation, dated rehearsal-record table at the foot.
  - *Look-up* template: generated-file banner ("do not edit by hand — regenerated by E48-T01"), anchor conventions, deep-link stability rule.
- **Front-matter schema** (YAML) shared by all three templates, machine-checkable so E48-Q01 and the CI freshness gate can assert reviewer presence.
- **Cross-link contract**: how in-app surfaces link out — SCR-119 Help & about → `docs/guide/`; SCR-058 methodology drawer → the detector-methodology section; SCR-019 setup checklist tasks → the guide section that completes each task. Link targets must be stable anchors, not line numbers.
- **Screenshot production standard**: which theme (dark default + one high-contrast example where E47 changed contrast), what must be redacted (account ids, balances, key fragments, tailnet addresses), the fixture dataset to use so screenshots are reproducible.

## Out of scope
- Writing any of the actual content (E48-S01, S02, T03, T04, T05).
- Redesigning SCR-119/SCR-058/SCR-018/SCR-019 — that is E48-D02; this ticket only defines the link contract those screens consume.
- A documentation website, static-site generator, search backend, or anything internet-facing.
- Changing `docs/plan/` structure itself; the planning tree is historical record and stays as it is.

## Acceptance criteria
```gherkin
Scenario: Each reading mode has its own template
  Given the three page templates are delivered
  Then the Do template contains an Expected observation for every step slot and a rehearsal-record table
  And the Learn template contains a permission callout bound to docs/plan/10-personas.md section 7
  And the Look-up template carries a generated-file banner
  And no template is a visual or structural duplicate of another

Scenario: Front-matter is machine-checkable
  Given the YAML front-matter schema
  When a document omits the non-author reviewer name or date
  Then a schema validation of that document fails with a message naming the missing field
  And the schema is delivered as a file E48-T01 can wire into CI

Scenario: A stressed reader finds the right runbook in under 60 seconds
  Given the research participants are given the IA map and a scenario "the fan-out partially failed at 03:00"
  When they navigate from the documented entry point
  Then they reach the fan-out partial-failure runbook in under 60 seconds without opening any other runbook first

Scenario: Deep links from the app are stable
  Given the cross-link contract
  When a documentation section is moved within its file
  Then its anchor is unchanged because anchors are explicit ids, not generated from headings
  And the contract states this rule explicitly

Scenario: A screenshot cannot leak
  Given the screenshot production standard
  Then it enumerates account ids, balances, API-key fragments and tailnet addresses as must-redact
  And it names the fixture dataset that makes screenshots reproducible without live data
```

## Technical notes / design
Front-matter schema (delivered as `docs/_meta/frontmatter.schema.json`, consumed by E48-T01's CI gate and E48-Q01):

```yaml
title: "Fan-out partial-failure recovery"
doc_type: learn | do | lookup
personas: [P1, P4]          # from docs/plan/10-personas.md; empty for lookup
applies_to_version: "1.1.0"
author: "<name>"
reviewer: "<name>"           # MUST differ from author (30-release-roadmap.md 9.4)
reviewed_on: "2027-09-04"    # ISO date
source_of_truth: "docs/plan/22-api-openapi.yaml"   # lookup docs only
rehearsed_on: ["2027-09-01"] # do docs only; appended by E48-S04
```

The `reviewer != author` and `reviewed_on` presence rules are the machine-enforceable half of the §9.4 Docs gate; the "was it a *real* review" half stays human and is Q01's job.

Anchor rule: every section that anything links to carries an explicit `<a id="rb-fanout-partial"></a>` immediately before its heading. Heading-derived anchors are forbidden for linked sections because rewording the heading silently breaks the app.

## Test plan
- **Research**: 2 participants × 5 lookup tasks, time-to-answer recorded pre-IA; the same tasks re-run against the IA map in the acceptance session.
- **Schema**: hand-write 6 fixture front-matter blocks (valid; missing reviewer; reviewer == author; bad date format; missing doc_type; unknown persona id) and assert the JSON Schema accepts/rejects each correctly. This fixture set is handed to E48-T01 as its CI test corpus.
- **Template review**: the Do template is dry-run against one existing draft runbook to confirm every field has a plausible value; a template field that is always "N/A" is removed rather than shipped.
- Coverage target: N/A (design artefact); the schema fixtures carry their own assertions in T01.

## Security notes
- Threat: documentation is an exfiltration surface. Screenshots and worked examples are the most common accidental leak of account ids, balances and key fragments (`docs/plan/04-security-program.md` §10.3 IR-02 exists precisely for "secret exposed in a screenshot").
- Control: the screenshot production standard mandates a fixture dataset and an explicit redaction list; E48-X02 audits every published artefact against it.
- Data classification: the IA and templates themselves are internal, non-sensitive. The content they will carry is internal-confidential.
- Review label: `security` not required on this ticket; its output feeds E48-X01/X02 which are labelled.

## Accessibility notes
- Templates must specify heading hierarchy (single h1, no skipped levels) so screen-reader landmark navigation works — `docs/plan/05-accessibility-standard.md`.
- Every screenshot in the Learn template has a mandatory alt-text slot with guidance ("describe what the reader must notice, not what is visible"); a screenshot with no alt text fails Q01.
- Do-template step tables must be real tables with header cells, not ASCII art, so they are navigable.
- Colour is never the only carrier of state in a documentation callout (contrast ≥4.5:1 for body, ≥3:1 for non-text indicators).

## Performance notes
Documentation is static markdown rendered by the repo host and by the in-app help links; no runtime budget from `docs/plan/06-performance-and-load-standard.md` applies. One constraint: the *Do* templates must be readable with no network — a runbook for "everything is down" cannot depend on fetching anything, so images in runbooks are forbidden and the templates say so.

## Observability
N/A for the artefact itself. The cross-link contract specifies that in-app help links emit the existing `help.about_viewed` analytics event (SCR-119) and no new event is introduced.

## Definition of Done
- [ ] Research findings written up (5–8 findings) and linked.
- [ ] IA map merged as a `docs/plan/17-ux-diagrams.md` addendum with a mermaid tree.
- [ ] Three templates delivered in Figma **and** as markdown skeleton files in `docs/_meta/templates/`.
- [ ] `docs/_meta/frontmatter.schema.json` delivered with its 6-case fixture corpus.
- [ ] Cross-link contract and screenshot standard merged.
- [ ] CDO or delegate sign-off recorded on the ticket; Architect has reviewed the IA map.
- [ ] Handed off to E48-S01/S02/T05 owners in a recorded session (`handoff` label satisfied).
- [ ] Status Done ≥2 sprints before Sprint 25 (design-ahead rule satisfied).

## Dependencies
- `blocked_by` E47: the accessibility conformance report is one of the documents the IA must place, and E47's contrast/theme decisions determine the screenshot theme standard. E47 runs S23–S25; only its early theme decisions are needed here, so the dependency is on E47's theme work, not its close — if E47 has not settled themes by mid-S23, the standard specifies dark-default only and a follow-up Chore adds the high-contrast example.
- Relies on `docs/plan/16-design-system-brief.md` tokens and `docs/plan/10-personas.md` §7 permission matrix being stable (both locked).

## Branch
`design/e48-docs-ia` — artefacts + schema + templates. PR size: small (schema + templates + one doc addendum), well under 400 LOC.

## References
- `docs/plan/17-ux-diagrams.md` (information architecture conventions)
- `docs/plan/16-design-system-brief.md` (tokens, type scale, density)
- `docs/plan/10-personas.md` §2–§7
- `docs/plan/30-release-roadmap.md` §9.4 (Docs gate: reviewed by someone who did not write them)
- `docs/plan/05-accessibility-standard.md`
- `docs/plan/04-security-program.md` §10.3 IR-02
"""

t("E48-D01", "Task",
  "Design the documentation information architecture and reading experience",
  ["design", "ux-research", "handoff", "type/design", "area/docs", "priority/p1"],
  "docs", "Sprint 23", "P1 High", "Product", "R10 Key-person", 3, "E48",
  ["E47"], D01)


D02 = """## Context
Four in-app surfaces make documentation claims to the user, and after 22 sprints of implementation they are the most likely places for the app to be *confidently wrong*:

- **SCR-119 Help & about** (`docs/plan/14-screens-catalogue.md` §SCR-119) — version, build hash, backend version, protocol version, changelog link, keyboard cheatsheet, glossary of order-flow terms, detector methodology link, guided-tour restart, diagnostics bundle export, licence/attribution list. Stories US-SET-009, US-OBS-007. Components CMP-001 Button, CMP-021 Link, CMP-036 KeyValueRow, CMP-051 Accordion, CMP-086 SettingsNav/SettingsLayout, CMP-096 WhatsNewPanel, CMP-207 BuildFooter.
- **SCR-058 Detector methodology drawer** — opened from any `(estimated)` chip; must explain per detector the heuristic, inputs, tunable thresholds, known false-positive modes, and the hard statement that Bybit provides no L3/MBO feed so these are proxies, not ground truth.
- **SCR-018 Guided tour / coach marks** — an 8-stop tour (chart, footprint, DOM, ticket, positions, rules, journal, panic buttons); its copy describes screens that have changed since the tour was written.
- **SCR-019 Setup checklist card** — per-role task list with deep links (add a live account, record a symbol, create a trade group, set risk caps, invite a second user, run the engine benchmark).

This is a **content-design** pass, not a visual redesign: the layouts are signed off and built. What changes is the words, the glossary, the methodology text, the per-role task copy, and the outward links now that `docs/guide/` exists (the link contract comes from E48-D01). Scheduled **Sprint 23**, two sprints ahead of E48-S03 in Sprint 25.

## Scope / Deliverables
- **SCR-119 content spec**: final copy for every KeyValueRow label (app version, engine version, backend version, protocol version, build hash, Bybit API version — per the screen's own design sign-off checklist); the update-check result states (up to date / update available / check failed) with exact strings; the copy-diagnostics control's statement of *what it copies* (US-OBS-007 requires secrets removed — the button copy must say so); links to the hotkey cheatsheet, the E47 accessibility statement, `docs/guide/`, and the SCR-058 drawer.
- **Glossary of order-flow terms** (lives in SCR-119, sourced from `docs/guide/`): every term the app puts on screen without explaining — footprint, delta, CVD, imbalance, absorption, POC, VAH/VAL, TPO, speed of tape, iceberg *(estimated)*, stop-run *(estimated)*, regime, queue position *(estimated)*, DOM heatmap, big trade, basis, funding, OI. Each entry: one-sentence definition, how CandleViewer computes it, and whether it is measured or estimated.
- **SCR-058 methodology copy** for each detector the product shipped, following the screen's mandated structure (heuristic · inputs · tunable thresholds · known false-positive modes · the no-L3/MBO statement). Every `(estimated)` chip in the product must have a matching entry; the deliverable includes the audit list proving one-to-one coverage.
- **SCR-018 tour copy** re-written against shipped screens, 8 stops, each ≤2 sentences, each naming the hotkey where one exists; plus the LIVE-mode rule already in the screen's sign-off checklist ("tour never blocks a trading control while LIVE") restated as copy guidance.
- **SCR-019 per-role task copy** for owner vs manager vs viewer, with the blocked-reason strings (`aria-disabled` tasks must carry the reason as *visible text* per the screen's a11y note — e.g. "Only the owner can add an exchange account").
- **CMP-096 WhatsNewPanel** copy pattern for the `1.1.0` GA entry, and **CMP-207 BuildFooter** / **CMP-094 HotkeyOverlay** label review.
- **Redline package**: for each surface, a before/after copy table so E48-S03 is a mechanical string change, not an interpretation exercise.

## Out of scope
- Any layout, spacing or component change to these screens — if content does not fit, the fix is shorter content, not a new layout; a genuine layout defect is filed as a Bug to E49.
- New components. Everything reuses CMP-036 KeyValueRow, CMP-051 Accordion, CMP-021 Link, CMP-096, CMP-207, CMP-094.
- Implementing anything (E48-S03).
- The detector *algorithms* — this ticket documents what shipped; a detector whose shipped behaviour differs from its spec is a Bug against the owning epic, not a copy change.

## Acceptance criteria
```gherkin
Scenario: Every estimated chip has methodology copy
  Given the audit list of every (estimated) chip shipped in the product
  When the SCR-058 content spec is reviewed
  Then each chip maps to exactly one methodology entry
  And each entry states the heuristic, the inputs, the tunable thresholds, the known false-positive modes and the no-L3/MBO statement

Scenario: The diagnostics button tells the truth
  Given the SCR-119 copy for the diagnostics-bundle control
  Then it names what the bundle contains (logs, metrics snapshot, configuration, health results, recent errors)
  And it states that secrets are removed and that generation fails loudly if any secret pattern is found
  And that wording matches the behaviour required by US-OBS-007

Scenario: A manager is never told to do something RBAC forbids
  Given the SCR-019 per-role copy
  When the manager task set is checked against the permission matrix in docs/plan/10-personas.md section 7
  Then no task is shown to a manager that the matrix forbids
  And every task that is shown-but-blocked carries a visible reason string, not only a disabled state

Scenario: Tour copy matches shipped screens
  Given the 8 tour stops
  When each stop is compared against the current build
  Then every named control, panel and hotkey exists with that name
  And any mismatch is recorded as a redline row, not silently corrected in the build

Scenario: Version rows are complete
  Given the SCR-119 design sign-off acceptance checklist
  Then app version, engine version, backend version, build hash and Bybit API version all have a specified label and value source
```

## Technical notes / design
Each redline row is delivered as: `surface | element id | current string | new string | source of truth | rationale`. "Source of truth" is a path+anchor (e.g. `docs/guide/glossary.md#cvd`) so E48-S03 can wire the link and E48-Q01 can verify it resolves.

Copy constraints: sentence case throughout; no exclamation marks; the word "simply" is banned; every *(estimated)* usage keeps the parenthetical lower-case form the product already uses so the existing chip styling and the screen catalogue's rule 2 ("any value derived from a heuristic proxy renders an `(estimated)` chip") remain consistent.

Version-row value sources: app version and build hash from the build metadata already surfaced by CMP-207 BuildFooter; backend version and protocol version from the existing health/version response used by SCR-119; Bybit API version from the exchange-adapter constant. No new endpoint is introduced by this ticket.

## Test plan
- **Coverage audit**: enumerate every `(estimated)` chip and every glossary-worthy on-screen term by walking the built app; assert one-to-one mapping to methodology/glossary entries. The enumeration list is the test artefact and is handed to E48-Q01.
- **RBAC copy check**: the SCR-019 task matrix is diffed against `docs/plan/10-personas.md` §7 cell by cell; any divergence blocks sign-off.
- **Readability**: each methodology entry read aloud by someone who is not an order-flow trader; if they cannot restate the false-positive mode in their own words, the entry is rewritten.
- **String-fit check**: every new string is pasted into the built component at the narrowest supported width to confirm it does not truncate (truncation is a content defect here, not a layout defect).

## Security notes
- Threat: the glossary and methodology text must not disclose anything about key handling, tailnet topology, or internal endpoints beyond what a user needs; SCR-119's licence/attribution list must not inadvertently enumerate internal package names that reveal architecture detail an attacker could use. (`docs/plan/04-security-program.md` — information disclosure.)
- Control: E48-X02 reviews the final strings; this ticket flags any string sourced from internal config for that review.
- The diagnostics-bundle copy must not overstate safety: US-OBS-007 guarantees secret-pattern scanning and loud failure, and the copy says exactly that and no more.
- Data classification: internal. No PII or credentials in any string.

## Accessibility notes
- All new strings must work as accessible names: the copy-diagnostics button's accessible name states what it copies (per SCR-119's a11y note).
- SCR-019 blocked-task reasons are **visible text**, not tooltip-only and not conveyed by the disabled state alone.
- SCR-058 drawer content is headings + prose; each detector section gets a heading so screen-reader users can jump between detectors.
- SCR-018 coach-mark copy must be meaningful when read out of visual context, since focus moves to the coach-mark content.
- Reading level: aim for plain language; `docs/plan/05-accessibility-standard.md` cognitive-load guidance applies.

## Performance notes
SCR-119 is specified to make no network calls except an explicit update check and to be fully available offline — so the glossary and methodology copy ship as bundled strings, not fetched documents. The content spec must therefore state a size budget: total added string payload ≤40 KB uncompressed, so the settings bundle does not regress the app-boot budget in `docs/plan/06-performance-and-load-standard.md`.

## Observability
No new events. Existing analytics stay as specified: `help.about_viewed`, `help.diagnostics_copied`, `help.update_check_requested` (SCR-119); `tour.started/step_viewed/dismissed/completed` (SCR-018); `setup.task_completed/checklist_dismissed` (SCR-019); `regime.explain_opened` and the other drawer-opening events for SCR-058.

## Definition of Done
- [ ] Redline package delivered for SCR-119, SCR-058, SCR-018, SCR-019, CMP-094, CMP-096, CMP-207.
- [ ] Glossary complete; every enumerated on-screen term covered.
- [ ] `(estimated)` chip → methodology entry mapping proven one-to-one, audit list attached.
- [ ] SCR-019 task copy diffed clean against the `10-personas.md` §7 permission matrix.
- [ ] Each affected screen's own "Design sign-off acceptance checklist" in `docs/plan/14-screens-catalogue.md` re-walked and every box ticked or explicitly waived.
- [ ] CDO or delegate sign-off; handoff session with the E48-S03 owner recorded.
- [ ] Status Done by end of Sprint 23 (≥2 sprints before Sprint 25).

## Dependencies
- `blocked_by` E48-D01 — the cross-link contract and front-matter/anchor rules determine every outward link target in this package.
- Consumes (does not change) E42's admin screens, E47's accessibility statement, and the detector work in E24/E25 whose shipped behaviour the methodology text must describe.

## Branch
`design/e48-help-content` — redlines + glossary + methodology copy as markdown under `docs/_meta/redlines/`. PR size: medium, content-only.

## References
- `docs/plan/14-screens-catalogue.md` SCR-018, SCR-019, SCR-058, SCR-119 (incl. their design sign-off acceptance checklists)
- `docs/plan/15-component-catalogue.md` CMP-036, CMP-051, CMP-094, CMP-096, CMP-207
- `docs/plan/11-user-stories.md` US-SET-009, US-OBS-007, US-ONB-007
- `docs/plan/10-personas.md` §7 permission matrix
- `docs/plan/05-accessibility-standard.md`
- `docs/plan/06-performance-and-load-standard.md` (app-boot budget)
"""

t("E48-D02", "Task",
  "Content-design pass on SCR-119, SCR-058, SCR-018 and SCR-019",
  ["design", "handoff", "type/design", "area/docs", "priority/p1", "a11y"],
  "web", "Sprint 23", "P1 High", "Product", "R10 Key-person", 3, "E48",
  ["E48-D01"], D02)


D03 = """## Context
E48-S03 changes strings and links across SCR-119, SCR-058, SCR-018, SCR-019, CMP-094 HotkeyOverlay, CMP-096 WhatsNewPanel and CMP-207 BuildFooter. `docs/plan/02-definition-of-ready-done.md` §3.2 makes `design-qa` default-on for UI Stories: the built screen is compared against the design spec by a designer or design-system-trained reviewer, and discrepancies are fixed or filed as a follow-up Bug with a priority.

This is the design-side verification that the redline package from E48-D02 landed exactly, that nothing truncates, that the outward links resolve to the anchors the IA contract promised, and that the three E48 documentation page templates were actually used by S01/S02/T03/T04/T05 rather than quietly ignored. It runs in **Sprint 26**, after the build, and is a gate on E48-T06's GA checklist.

## Scope / Deliverables
- **Redline verification**: every row of the E48-D02 redline package checked against the GA-candidate build — string present, exact, in the right element.
- **Truncation and density sweep**: each affected surface at the narrowest supported width and at both density settings from `docs/plan/16-design-system-brief.md`; any clipped or wrapped-badly string recorded.
- **Link resolution sweep**: every outward link from SCR-119, SCR-058 and SCR-019 followed; each must land on an explicit anchor in the `docs/` tree (per E48-D01's anchor rule), not a 404 and not the top of a long file.
- **Template conformance**: sample at least one document from each of the six E48 document sets and confirm it uses the correct Learn/Do/Look-up template and carries valid front-matter.
- **Token conformance** on any element E48-S03 touched: type scale, spacing, colour tokens — no hard-coded values introduced while editing strings.
- **Findings log**: each finding classified *fix-now* (in E48-S03's PR), *Bug to E49*, or *accepted with written rationale*; no third category and no silent pass.

## Out of scope
- Functional testing — that is E48-Q01/Q03.
- Accessibility auditing as a discipline — E47 owns WCAG conformance; this ticket only checks that E48's own changes did not regress what E47 fixed, and files anything it finds to E47 or E49.
- Re-opening content decisions settled in E48-D02.

## Acceptance criteria
```gherkin
Scenario: Every redline row is verified
  Given the E48-D02 redline package
  When each row is checked against the GA-candidate build
  Then each row is marked verified, or a finding is logged with a classification
  And the count of verified plus logged rows equals the total row count

Scenario: No outward link is broken
  Given every documentation link on SCR-119, SCR-058 and SCR-019
  When each is followed in the GA candidate
  Then it resolves to an explicit anchor in the docs tree
  And no link resolves to a missing file, a missing anchor, or the top of a file when a section anchor was specified

Scenario: A string that truncates is a finding, not a shrug
  Given the narrowest supported width and the compact density setting
  When each affected surface is rendered
  Then no string is visually clipped
  And any clipped string is logged as fix-now with the shortened replacement proposed in the log

Scenario: Templates were actually used
  Given one sampled document from each of the six E48 document sets
  Then each uses the template matching its doc_type
  And each has front-matter that passes the schema from E48-D01, including a reviewer who is not the author

Scenario: Findings cannot be silently dropped
  Given the findings log at sign-off
  Then every entry is classified fix-now, Bug-to-E49, or accepted-with-rationale
  And every accepted entry names the person who accepted it and why
```

## Technical notes / design
Run against the **GA release candidate build**, not `main`, so that what is signed off is what ships (`docs/plan/07-release-and-prr.md` §4). Use the same fixture dataset named in E48-D01's screenshot standard so the reviewer sees reproducible content and no live account data.

Check order matters: link resolution first (it can invalidate whole sections of the content check), then redline rows, then truncation, then tokens. Record the build tag and date on the log; the log is an input artefact to E48-Q03's evidence pack and to the PRR.

## Test plan
- Manual structured pass over 7 surfaces × (2 densities × 2 widths) = 28 renders, plus one pass per sampled document (6).
- Automated assist: a link-checker run over the `docs/` tree and over the extracted in-app link table (reuse the checker E48-T01 builds for the CI freshness gate rather than writing a second one).
- Re-test loop: fix-now findings are re-verified in the same sprint; the ticket cannot be Done with an unverified fix-now finding outstanding.

## Security notes
- The reviewer works with the fixture dataset; if any live account identifier, balance, or key fragment appears in a screenshot taken during this pass, it is an immediate finding routed to E48-X02 and handled under `docs/plan/04-security-program.md` §10.3 IR-02 if it left the machine.
- Any documentation link discovered pointing outside the repo (an external URL) is a finding: this system is Tailscale-only and its help surfaces must not depend on internet reachability.

## Accessibility notes
- Confirm SCR-019 blocked-task reasons remain visible text; confirm the copy-diagnostics accessible name still states what it copies; confirm SCR-058 detector sections still expose headings.
- Confirm no string change broke a heading hierarchy or an `aria-label` binding.
- Any true WCAG failure is filed to E47, not fixed here, so conformance evidence stays owned in one place.

## Performance notes
Verify the added string payload stayed within the ≤40 KB budget E48-D02 set, by comparing the settings-bundle size on the GA candidate against the pre-E48 baseline; a regression beyond that is a finding against `docs/plan/06-performance-and-load-standard.md` app-boot budget and is routed to E46.

## Observability
Confirm E48-S03 introduced no new analytics events and did not remove the existing ones (`help.about_viewed`, `help.diagnostics_copied`, `help.update_check_requested`, `tour.*`, `setup.*`).

## Definition of Done
- [ ] All redline rows verified or logged.
- [ ] Link sweep clean; zero unresolved anchors.
- [ ] Truncation sweep clean at both densities and the narrowest width.
- [ ] Template/front-matter conformance confirmed on all six document sets.
- [ ] Findings log complete, every entry classified, fix-now items re-verified.
- [ ] Designer sign-off comment posted on E48-S03 (satisfying its `design-qa` DoD item).
- [ ] Log attached to E48-Q03's evidence pack.

## Dependencies
- `blocked_by` E48-S03 (the build under review), E48-D02 (the redline package), E48-T01 (the link checker and the published reference the links point into).
- Relies on the GA release candidate existing — coordinate with E48-T06's release-branch cut.

## Branch
`design/e48-docs-design-qa` — findings log only (`docs/_meta/design-qa/e48-log.md`). No production code changes originate here; fixes land in E48-S03's branch.

## References
- `docs/plan/02-definition-of-ready-done.md` §3.2 (design-qa DoD)
- `docs/plan/14-screens-catalogue.md` SCR-018, SCR-019, SCR-058, SCR-119
- `docs/plan/15-component-catalogue.md` CMP-094, CMP-096, CMP-207
- `docs/plan/16-design-system-brief.md` (tokens, density)
- `docs/plan/07-release-and-prr.md` §4 (release candidate)
"""

t("E48-D03", "Task",
  "Design QA of the documentation and in-app help surfaces",
  ["design-qa", "design", "type/design", "area/docs", "priority/p2"],
  "web", "Sprint 26", "P2 Medium", "Product", "R10 Key-person", 2, "E48",
  ["E48-S03", "E48-D02", "E48-T01"], D03)
