"""The metric catalogue — every metric in `20-architecture.md` §12.1 (E04-T03).

Metric names are a contract with dashboards (E04-S01) and alert rules
(E04-T05), so every name is declared here even when its owning module ships
later. `status="live"` entries are registered by `register_r0()` in every
process; `status="planned"` entries record the owning epic that implements
them and register no samples until then. SR-125 security metrics are declared
here too, so E09/E27/E35/E43 have names to implement against.

A golden snapshot test (`tests/unit/observability/test_metrics_catalogue.py`)
fails on any unreviewed name/label change.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Literal

from candleviewer.observability.latency import E2E_BUCKETS, STAGE_BUCKETS
from candleviewer.observability.metrics import BoundedMetric, MetricKind, Metrics

Status = Literal["live", "planned"]

#: Loop lag: buckets straddle the 50 ms p99 target and the 100 ms alert
#: threshold so each lands on its own bucket edge (06-performance §2).
LOOP_LAG_BUCKETS: Final = (
    0.001,
    0.005,
    0.01,
    0.025,
    0.05,
    0.075,
    0.1,
    0.25,
    0.5,
    1.0,
    2.5,
)
#: Fan-out: edges around the 20 ms p99 budget.
FANOUT_BUCKETS: Final = (0.001, 0.0025, 0.005, 0.01, 0.015, 0.02, 0.03, 0.05, 0.1, 0.25)
#: Per-engine CPU time per batch.
ENGINE_BUCKETS: Final = (
    0.0001,
    0.00025,
    0.0005,
    0.001,
    0.0025,
    0.005,
    0.01,
    0.025,
    0.05,
    0.1,
)
#: Storage round-trips.
STORAGE_BUCKETS: Final = (
    0.001,
    0.0025,
    0.005,
    0.01,
    0.025,
    0.05,
    0.1,
    0.25,
    0.5,
    1.0,
    5.0,
)
#: Order submit click→ack, p99 ≤ 500 ms.
SUBMIT_BUCKETS: Final = (0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 2.0, 5.0)
#: Statechart transition latency.
TRANSITION_BUCKETS: Final = (
    0.00005,
    0.0001,
    0.00025,
    0.0005,
    0.001,
    0.0025,
    0.005,
    0.01,
)
#: `screen` label cap for pushed frontend series (keeps /metrics < 50 ms).
FE_SCREEN_MAX_SERIES: Final = 8
#: Frontend pushed histograms (client pre-buckets on the same edges).
FE_FRAME_BUCKETS: Final = (4.0, 8.0, 12.0, 16.0, 20.0, 33.0, 50.0, 100.0)
FE_DECODE_BUCKETS: Final = (0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 5.0, 10.0)


@dataclass(frozen=True, slots=True)
class MetricSpec:
    name: str
    kind: MetricKind
    unit: str
    labels: tuple[str, ...]
    help: str
    alert: str
    status: Status
    owner_epic: str
    buckets: tuple[float, ...] | None = None
    max_series: int = 200
    #: Live, but created at module level by its owner and served by a `ReexportCollector`
    #: (e.g. `bars.metrics.export_bars_metrics`); `register_r0()` must not register it twice.
    exported: bool = False


def _s(
    name: str,
    kind: MetricKind,
    unit: str,
    labels: tuple[str, ...],
    help_text: str,
    alert: str,
    status: Status,
    owner: str,
    buckets: tuple[float, ...] | None = None,
    max_series: int = 200,
    exported: bool = False,
) -> MetricSpec:
    return MetricSpec(
        name, kind, unit, labels, help_text, alert, status, owner, buckets, max_series, exported
    )


_L: Final[Status] = "live"
_P: Final[Status] = "planned"

CATALOGUE: Final[tuple[MetricSpec, ...]] = (
    # --- Runtime / R0 live -------------------------------------------------
    # --- Support bundle (E04-S02) -------------------------------------------
    _s(
        "support_bundle_generations_total",
        "counter",
        "generations",
        ("result",),
        "Support bundle generations by result (ok/error/timeout/secret_detected).",
        'result="secret_detected" > 0 (ticket)',
        _L,
        "E04",
        max_series=8,
    ),
    _s(
        "support_bundle_duration_seconds",
        "histogram",
        "seconds",
        (),
        "Wall time to generate a support bundle.",
        "n/a",
        _L,
        "E04",
        (1.0, 5.0, 15.0, 30.0, 60.0, 120.0),
    ),
    _s(
        "support_bundle_bytes",
        "histogram",
        "bytes",
        (),
        "Size of a generated support bundle.",
        "n/a",
        _L,
        "E04",
        (1e5, 1e6, 1e7, 5e7, 1e8, 2e8),
    ),
    _s(
        "event_loop_lag_seconds",
        "histogram",
        "seconds",
        (),
        "asyncio loop overshoot sampled every 100 ms.",
        "p99 > 0.1 for 5m",
        _L,
        "E04",
        LOOP_LAG_BUCKETS,
    ),
    _s(
        "ws_connection_state",
        "gauge",
        "state",
        ("socket",),
        "Exchange socket state: 1 up, 0 down.",
        "== 0 for 10s",
        _L,
        "E04",
        max_series=16,
    ),
    _s(
        "ws_messages_total",
        "counter",
        "messages",
        ("topic",),
        "Exchange WS messages received per topic.",
        "throughput dashboard",
        _L,
        "E04",
        max_series=64,
    ),
    _s(
        "ws_message_bytes_total",
        "counter",
        "bytes",
        (),
        "Exchange WS payload bytes received.",
        "cost sizing",
        _L,
        "E04",
    ),
    _s(
        "topic_staleness_seconds",
        "gauge",
        "seconds",
        ("topic",),
        "Seconds since the topic last updated, computed at scrape time.",
        "book > 2s, trades > 10s",
        _L,
        "E04",
        max_series=64,
    ),
    _s(
        "ingest_queue_depth",
        "gauge",
        "items",
        ("stage",),
        "Items waiting in each bounded ingestion queue.",
        "saturation",
        _L,
        "E04",
        max_series=16,
    ),
    _s(
        "bars_built_total",
        "counter",
        "bars",
        ("symbol", "kind"),
        "Bars closed by a builder (24 §3.3, E12-S01).",
        "none",
        _L,
        "E12",
        exported=True,
        max_series=400,
    ),
    _s(
        "bars_amended_total",
        "counter",
        "bars",
        ("symbol",),
        "Closed bars re-emitted after a late trade within 60 s.",
        "none",
        _L,
        "E12",
        exported=True,
        max_series=80,
    ),
    _s(
        "bars_late_trade_dropped_total",
        "counter",
        "trades",
        ("symbol", "reason"),
        "Late trades applied to no bar (older than 60 s, or interval had no bar).",
        "sustained growth = clock/ingest lag",
        _L,
        "E12",
        exported=True,
        max_series=80,
    ),
    _s(
        "bar_volume_splits_total",
        "counter",
        "trades",
        ("symbol",),
        "Trades split across volume bars (24 §3.3, E12-S02).",
        "~100% of trades = misconfigured threshold",
        _L,
        "E12",
        exported=True,
        max_series=40,
    ),
    _s(
        "bars_partial_series_total",
        "counter",
        "series",
        ("kind",),
        "Activity-bar series whose first bar is partial (tape starts mid-bar).",
        "none",
        _L,
        "E12",
        exported=True,
        max_series=6,
    ),
    # --- Bar builder set (E12-T03); served by bars.metrics.export_bars_metrics ------
    _s(
        "bar_builder_specs_in_use",
        "gauge",
        "specs",
        ("symbol",),
        "Active bar specs per symbol (cap 32, SR-E12-04).",
        "near the cap = a client opening many series",
        _L,
        "E12",
        max_series=40,
        exported=True,
    ),
    _s(
        "bar_builder_fanout_latency_seconds",
        "histogram",
        "seconds",
        (),
        "Time to fan one trade to every builder of its symbol.",
        "p95 > 1 ms eats the US-MKT-006 20 ms budget",
        _L,
        "E12",
        (0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.02),
        exported=True,
    ),
    _s(
        "bar_builder_cold_start_seconds",
        "histogram",
        "seconds",
        (),
        "Restore + tape replay time before a spec goes live.",
        "> 60 s = blob cadence broken",
        _L,
        "E12",
        (0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 30.0),
        exported=True,
    ),
    _s(
        "bar_state_snapshots_written_total",
        "counter",
        "blobs",
        (),
        "Builder state blobs written (every 60 s per series).",
        "flat while specs are active = persistence stalled",
        _L,
        "E12",
        exported=True,
    ),
    _s(
        "bars_blob_discarded_total",
        "counter",
        "blobs",
        ("reason",),
        "State blobs discarded on restore (corrupt, too_large, version, wrong_series, ...).",
        "any = cold start; investigate disk",
        _L,
        "E12",
        max_series=10,
        exported=True,
    ),
    _s(
        "bar_builder_cold_starts_total",
        "counter",
        "specs",
        (),
        "Specs started without a usable state blob.",
        "none",
        _L,
        "E12",
        exported=True,
    ),
    _s(
        "bars_spec_cap_rejected_total",
        "counter",
        "registrations",
        ("reason",),
        "Spec registrations refused by a cap (per-user, per-symbol, process-wide).",
        "sustained = abuse or caps too low (SR-E12-04)",
        _L,
        "E12",
        max_series=3,
        exported=True,
    ),
    _s(
        "bar_builder_quarantined_total",
        "counter",
        "series",
        ("reason",),
        "Series removed after their builder raised (builder_error) or bars tasks that died.",
        "any = a builder defect; series stopped",
        _L,
        "E12",
        max_series=2,
        exported=True,
    ),
    _s(
        "bar_emit_sink_errors_total",
        "counter",
        "emissions",
        ("reason",),
        "Bar emissions a sink (questdb, ws) failed to accept.",
        "any = bars missing downstream",
        _L,
        "E12",
        max_series=4,
        exported=True,
    ),
    _s(
        "book_resync_total",
        "counter",
        "resyncs",
        ("symbol", "reason"),
        "Order-book resyncs from snapshot.",
        "> 5/min",
        _L,
        "E04",
        max_series=80,
    ),
    _s(
        "engine_process_seconds",
        "histogram",
        "seconds",
        ("engine",),
        "CPU time per engine batch.",
        "CPU budget per engine",
        _L,
        "E04",
        ENGINE_BUCKETS,
        max_series=16,
    ),
    _s(
        "pg_pool_in_use",
        "gauge",
        "connections",
        (),
        "Postgres pool connections checked out.",
        "saturation",
        _L,
        "E04",
    ),
    _s(
        "pg_query_seconds",
        "histogram",
        "seconds",
        (),
        "Postgres query latency.",
        "saturation",
        _L,
        "E04",
        STORAGE_BUCKETS,
    ),
    _s(
        "questdb_write_seconds",
        "histogram",
        "seconds",
        (),
        "QuestDB ILP write latency.",
        "saturation",
        _L,
        "E04",
        STORAGE_BUCKETS,
    ),
    _s(
        "bybit_rate_remaining",
        "gauge",
        "requests",
        ("endpoint_group",),
        "Remaining per-UID exchange rate budget per endpoint group (US-OBS-005).",
        "budget health",
        _L,
        "E04",
        max_series=16,
    ),
    _s(
        "oms_rate_reject_total",
        "counter",
        "rejects",
        (),
        "Orders rejected by the rate-limit governor or exchange 10006/10018 (SR-125).",
        "budget health",
        _L,
        "E04",
    ),
    # --- Statechart (E50) ---------------------------------------------------
    _s(
        "cv_machine_live_count",
        "gauge",
        "interpreters",
        ("kind",),
        "Live interpreters per machine family.",
        "monotonic growth",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_deferred_depth",
        "gauge",
        "events",
        ("kind",),
        "Deferral-buffer depth.",
        "> 0 for 5s",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_unhandled_events_total",
        "counter",
        "events",
        ("kind", "event"),
        "Events with no handler.",
        "undeclared event name",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_quarantined_total",
        "counter",
        "transitions",
        ("kind",),
        "Faulted transitions.",
        "page P1 on any",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_transition_seconds",
        "histogram",
        "seconds",
        ("kind",),
        "Transition latency.",
        ">= 8000 ev/s aggregate",
        _P,
        "E50",
        TRANSITION_BUCKETS,
    ),
    _s(
        "cv_machine_chain_trips_total",
        "counter",
        "trips",
        ("kind",),
        "Runaway-chain latches (CV-C63).",
        "page P1 on any",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_dropped_receipts_total",
        "counter",
        "receipts",
        ("kind",),
        "Dropped receipts (CV-C69).",
        "alert on any",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_transitions_total",
        "counter",
        "transitions",
        ("kind",),
        "Committed transitions per machine family (E50-T60).",
        "rate drop to 0 on a busy family",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_timer_handles",
        "gauge",
        "handles",
        ("kind",),
        "Live `after:` timer handles per machine family (E50-T60).",
        "monotonic growth",
        _P,
        "E50",
    ),
    _s(
        "cv_machine_send_refused_total",
        "counter",
        "events",
        ("kind", "reason"),
        "Inbox overflow refusals.",
        "order lane pages",
        _P,
        "E50",
    ),
    _s(
        "cv_statechart_library_info",
        "gauge",
        "info",
        ("version", "sha256"),
        "Pinned xstate-statemachine build identity.",
        "mismatch fails readiness",
        _P,
        "E50",
        max_series=2,
    ),
    # --- Rules / gateway / OMS ---------------------------------------------
    _s(
        "cv_alert_compile_rejected_total",
        "counter",
        "rejections",
        ("reason",),
        "Alert compiles refused, by reason.",
        "action_node > 0 (security review)",
        _P,
        "E40",
        max_series=8,
    ),
    _s(
        "cv_alert_compile_seconds",
        "histogram",
        "seconds",
        (),
        "Alert compile + validate time.",
        "p95 > 0.3s",
        _P,
        "E40",
        buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 1.0),
    ),
    _s(
        "cv_alert_eval_latency_seconds",
        "histogram",
        "seconds",
        (),
        "Alert condition met -> delivery committed (E40-T03).",
        "p95 > 1s",
        _P,
        "E40",
        buckets=(0.001, 0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
    ),
    _s(
        "cv_alerts_armed",
        "gauge",
        "alerts",
        (),
        "Armed alerts in the evaluator.",
        "dashboard only",
        _P,
        "E40",
    ),
    _s(
        "cv_alert_subscriptions",
        "gauge",
        "subscriptions",
        (),
        "Distinct condition_hash subscriptions.",
        "> cv_alerts_armed (sharing lost)",
        _P,
        "E40",
    ),
    _s(
        "cv_alert_fires_total",
        "counter",
        "fires",
        ("trigger_mode",),
        "Alert firings.",
        "dashboard only",
        _P,
        "E40",
        max_series=3,
    ),
    _s(
        "cv_alert_suppressed_total",
        "counter",
        "fires",
        ("reason",),
        "Gated alert firings (storm|snoozed|muted|expired|cooldown).",
        "storm rate > 0 for 10m",
        _P,
        "E40",
        max_series=5,
    ),
    _s(
        "cv_alert_autodisarmed_total",
        "counter",
        "alerts",
        ("reason",),
        "Alerts auto-disarmed on source loss.",
        "alert on any",
        _P,
        "E40",
        max_series=4,
    ),
    _s(
        "cv_alert_eval_queue_depth",
        "gauge",
        "ticks",
        (),
        "Alert evaluation queue depth.",
        "> 512 for 1m",
        _P,
        "E40",
    ),
    _s(
        "cv_alert_eval_dropped_total",
        "counter",
        "ticks",
        (),
        "Alert ticks shed by the bounded queue (drop-oldest).",
        "alert on any",
        _P,
        "E40",
    ),
    _s(
        "cv_alert_delivery_total",
        "counter",
        "deliveries",
        ("transport", "state"),
        "Settled alert deliveries by transport (channel) and terminal state (E40-T04).",
        "failed rate > 0 for 10m",
        _P,
        "E40",
        max_series=15,
    ),
    _s(
        "cv_alert_delivery_latency_seconds",
        "histogram",
        "seconds",
        ("transport",),
        "Alert firing committed -> delivery sent (E40-T04).",
        "p95 > 5s",
        _P,
        "E40",
        buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 30.0, 300.0),
        max_series=5,
    ),
    _s(
        "cv_alert_delivery_attempts",
        "histogram",
        "attempts",
        (),
        "Adapter attempts per settled alert delivery (E40-T04).",
        "dashboard only",
        _P,
        "E40",
        buckets=(1, 2, 3, 4, 6, 8, 10),
    ),
    _s(
        "cv_outbox_depth",
        "gauge",
        "rows",
        ("topic",),
        "Unprocessed, not-dead outbox rows by topic.",
        "alert.deliver > 100 for 5m",
        _P,
        "E40",
        max_series=8,
    ),
    _s(
        "cv_outbox_dead_total",
        "counter",
        "rows",
        ("topic",),
        "Outbox rows dead-lettered after max_attempts.",
        "alert on any increase",
        _P,
        "E40",
        max_series=8,
    ),
    _s(
        "cv_rule_prefilter_rejection_ratio",
        "gauge",
        "ratio",
        (),
        "Rule prefilter rejection ratio.",
        "< 0.99 disables dispatch",
        _P,
        "E35",
    ),
    _s(
        "ws_clients",
        "gauge",
        "clients",
        (),
        "Connected gateway WS clients.",
        "capacity",
        _P,
        "E17",
    ),
    _s(
        "ws_topics_per_client",
        "gauge",
        "topics",
        (),
        "Max topics subscribed by a single client.",
        "capacity",
        _P,
        "E17",
    ),
    _s(
        "ws_conflated_total",
        "counter",
        "frames",
        (),
        "Frames conflated for slow clients.",
        "client health",
        _P,
        "E17",
    ),
    _s(
        "ws_resync_total",
        "counter",
        "resyncs",
        (),
        "Client resyncs (SR-125 WS desync rate).",
        "client health",
        _P,
        "E17",
    ),
    _s(
        "ws_slow_conn_total",
        "counter",
        "connections",
        (),
        "Slow-consumer disconnects.",
        "client health",
        _P,
        "E17",
    ),
    _s(
        "ws_fanout_latency_seconds",
        "histogram",
        "seconds",
        (),
        "Bus to socket fan-out latency.",
        "p99 > 0.02",
        _P,
        "E17",
        FANOUT_BUCKETS,
    ),
    _s(
        "order_submit_seconds",
        "histogram",
        "seconds",
        ("transport",),
        "Order click-to-ack latency.",
        "p99 > 0.5",
        _P,
        "E29",
        SUBMIT_BUCKETS,
    ),
    _s(
        "orders_total",
        "counter",
        "orders",
        ("state",),
        "Orders by terminal state.",
        "reject rate",
        _P,
        "E29",
    ),
    _s(
        "oms_unknown_orders",
        "gauge",
        "orders",
        (),
        "Orders on the exchange unknown to the OMS.",
        "> 0 for 60s (page)",
        _P,
        "E45",
    ),
    _s(
        "naked_position_alerts_total",
        "counter",
        "alerts",
        (),
        "Positions observed without a native SL.",
        "page immediately",
        _P,
        "E32",
    ),
    _s(
        "bybit_clock_drift_ms",
        "gauge",
        "milliseconds",
        (),
        "Local vs exchange clock drift (SR-125).",
        "> 1500",
        _P,
        "E08",
    ),
    _s(
        "rule_evaluations_total",
        "counter",
        "evaluations",
        (),
        "Rule evaluations.",
        "rule storm",
        _P,
        "E35",
    ),
    _s(
        "rule_fires_total",
        "counter",
        "fires",
        ("rule_id",),
        "Rule fires per rule.",
        "rule storm",
        _P,
        "E35",
        max_series=100,
    ),
    _s(
        "rule_autodisarm_total",
        "counter",
        "disarms",
        (),
        "Rules auto-disarmed.",
        "rule storm",
        _P,
        "E35",
    ),
    _s(
        "recorder_rows_total",
        "counter",
        "rows",
        ("stream",),
        "Rows written by the recorder.",
        "ingest rate",
        _P,
        "E16",
    ),
    _s(
        "recorder_spill_bytes",
        "gauge",
        "bytes",
        (),
        "Recorder spill-file size.",
        "spill growth",
        _P,
        "E16",
    ),
    _s(
        "disk_used_ratio",
        "gauge",
        "ratio",
        (),
        "Data volume used ratio (SR-125 disk high-watermark).",
        "> 0.8; page > 0.95",
        _P,
        "E16",
    ),
    # --- SR-125 security metrics (planned) ----------------------------------
    _s(
        "auth_login_failures_total",
        "counter",
        "failures",
        ("method",),
        "Failed logins.",
        "brute force",
        _P,
        "E09",
    ),
    _s(
        "auth_lockouts_total",
        "counter",
        "lockouts",
        (),
        "Account lockouts.",
        "brute force",
        _P,
        "E09",
    ),
    _s(
        "auth_stepup_failures_total",
        "counter",
        "failures",
        (),
        "Step-up (TOTP) failures.",
        "credential attack",
        _P,
        "E09",
    ),
    _s(
        "authz_denied_total",
        "counter",
        "denials",
        ("permission",),
        "Permission-check failures.",
        "privilege probing",
        _P,
        "E09",
    ),
    _s(
        "credential_verification_failures_total",
        "counter",
        "failures",
        ("reason",),
        "Exchange credential verification failures.",
        "key revoked/withdrawal on",
        _P,
        "E27",
    ),
    _s(
        "rule_circuit_breaker_trips_total",
        "counter",
        "trips",
        (),
        "Rule circuit-breaker trips.",
        "alert on any",
        _P,
        "E35",
    ),
    _s(
        "audit_chain_verification_failures_total",
        "counter",
        "failures",
        (),
        "Audit hash-chain verification failures.",
        "page on any",
        _P,
        "E43",
    ),
    _s(
        "egress_ip_changes_total",
        "counter",
        "changes",
        (),
        "Detected egress IP changes (exchange key IP allow-list).",
        "alert on any",
        _P,
        "E43",
    ),
    # --- Latency budget (E04-T06, US-OBS-002) -------------------------------
    _s(
        "ingest_stage_seconds",
        "histogram",
        "seconds",
        ("stage",),
        "Per-stage tick latency (exchange|parse|derive|fanout); attribution only.",
        "LatencyBudgetBreach names the stage",
        _L,
        "E04",
        STAGE_BUCKETS,
        max_series=4,
    ),
    _s(
        "e2e_tick_to_paint_seconds",
        "histogram",
        "seconds",
        (),
        "Paired 1-in-N tick receipt to client paint (budget #3).",
        "p95 > 0.25 for 60s",
        _L,
        "E04",
        E2E_BUCKETS,
    ),
    _s(
        "telemetry_rejected_total",
        "counter",
        "payloads",
        ("reason",),
        "Frontend telemetry payloads rejected, by closed reason.",
        "abuse / client bug",
        _L,
        "E04",
        max_series=4,
    ),
    # --- Frontend (pushed; ingested by E04-T06) ------------------------------
    _s(
        "fe_frame_time_ms",
        "histogram",
        "milliseconds",
        ("screen",),
        "Frontend frame time.",
        "engine regression",
        _L,
        "E04",
        FE_FRAME_BUCKETS,
        max_series=FE_SCREEN_MAX_SERIES,
    ),
    _s(
        "fe_dropped_frames_total",
        "counter",
        "frames",
        ("screen",),
        "Frontend dropped frames.",
        "engine regression",
        _L,
        "E04",
        max_series=FE_SCREEN_MAX_SERIES,
    ),
    _s(
        "fe_ws_decode_ms",
        "histogram",
        "milliseconds",
        ("screen",),
        "Frontend WS decode time.",
        "p95 > 4",
        _L,
        "E04",
        FE_DECODE_BUCKETS,
        max_series=FE_SCREEN_MAX_SERIES,
    ),
    _s(
        "fe_gpu_memory_mb",
        "gauge",
        "megabytes",
        ("screen",),
        "Frontend GPU memory.",
        "engine regression",
        _L,
        "E04",
        max_series=FE_SCREEN_MAX_SERIES,
    ),
)

#: Keys of the fallback snapshot written to the log every 5 min.
SNAPSHOT_KEYS: Final[tuple[str, ...]] = (
    "ws_connection_state",
    "topic_staleness_seconds",
    "ingest_queue_depth",
    "pg_pool_in_use",
    "bybit_rate_remaining",
    "oms_rate_reject_total",
    "ws_messages_total",
    "metric_cardinality_breach_total",
    "metrics_registry_series",
)


def live_specs() -> tuple[MetricSpec, ...]:
    return tuple(s for s in CATALOGUE if s.status == "live")


def registered_specs() -> tuple[MetricSpec, ...]:
    """Live entries `register_r0()` owns (re-exported ones are served by their module)."""
    return tuple(s for s in live_specs() if not s.exported)


def register_r0(metrics: Metrics) -> dict[str, BoundedMetric]:
    """Register every `live` catalogue entry on `metrics`; idempotent."""
    out: dict[str, BoundedMetric] = {}
    for spec in registered_specs():
        if spec.kind == "histogram" and spec.buckets is not None:
            out[spec.name] = metrics.histogram(
                spec.name,
                spec.help,
                spec.labels,
                buckets=spec.buckets,
                max_series=spec.max_series,
            )
        elif spec.kind == "counter":
            out[spec.name] = metrics.counter(
                spec.name, spec.help, spec.labels, max_series=spec.max_series
            )
        else:
            out[spec.name] = metrics.gauge(
                spec.name, spec.help, spec.labels, max_series=spec.max_series
            )
        if not spec.labels:
            # Pre-bind so label-less metrics export an env-labelled sample at once.
            out[spec.name].child()
    return out
